### DISCUSSION TITLE
Access containerd.sock from host

### DISCUSSION THREAD

**Discussion by simonhoss** [lima-vm/lima#1033] [Q&A]
Hey

I want to access containerd.sock from the host.

I tried the following settings:

```yml
portForwards:
 - guestSocket: "/run/containerd/containerd.sock"
   hostSocket: containerd.sock
```

When I try to connect to the containerd.sock on my host. It doesn't work. 

`rpc error: code = Unavailable desc = connection closed before server preface received`

Any ideas? 

Thanks
