### DISCUSSION TITLE
Direct access to containerd socket?

### DISCUSSION THREAD

**Discussion by deitch** [lima-vm/lima#1275] [Q&A] [answered]
### Description

Is there a way to get direct access to a containerd socket running on a lima VM? The use case I am thinking of is, rather than having to execute a cli - `limactl shell <name> nerdctl` (or `limactl shell <name> ctr` - we could communicate directly via `ctr` or the library.

**Comment by jandubois** [comment, marked as answer]
There is nothing magical about it; you can just forward it from the VM to the host, the same way the docker example does it:

https://github.com/lima-vm/lima/blob/baca0e7ecd1b3515f471d2eb60fdbb0864e9a487/examples/docker.yaml#L77-L79

Keep in mind though that not all operations can be performed over the socket, but might need direct access to the storage layer (e.g. `nerdctl build`).

**Reply by deitch** [reply]
Oh, I need to try that. Thanks @jandubois

**Reply by afbjorklund** [reply]
For the special case of `docker build` (or `docker load`), you might want to try out the `nerdctl.sock` that I did:

https://github.com/afbjorklund/nerdctld

It serves as an API example, on how the build context (or archive context) can be transferred over to the VM.

Since `ctr` and `buildctl` doesn't have any mechanisms to do it, there are not too many options for remoting...

---

Should make a lima example for it (the main use case was minikube), but it least it has some packages now.

https://github.com/afbjorklund/nerdctld/releases/latest

EDIT: Here is the example, show how that it can be accessed:

https://github.com/afbjorklund/nerdctld/blob/main/lima.yaml

**Reply by afbjorklund** [reply]
Then again, promised myself after the Podman adventures (remember varlink) that I shouldn't try to re-invent Docker again.

If you want to access `podman` or `nerdctl`, then you probably _should_ be using SSH and CLI ? With the optional unix sockets.

**Reply by deitch** [reply]
That didn't quite work. The problem is finding access to the containerd socket itself. It doesn't appear to be in `/run` at all; I suspect `nerdctl` is doing something interesting in terms of namespaces when it runs? E.g. I can run `nerdctl image ls` and get results, but `ctr image ls` just hangs as it cannot find the socket.

**Reply by deitch** [reply]
Actually, for my specific use case, I am more than happy to use the containerd client API

**Reply by afbjorklund** [reply]
If you want to use the low level clients, there are more things needed...

See https://github.com/containerd/containerd/blob/main/docs/rootless.md and "The Hard Way"

**Reply by afbjorklund** [reply]
Running as root would also work, but then the example would need to be modified a bit (which systemd, which path)

Similar to https://github.com/lima-vm/lima/blob/master/examples/docker-rootful.yaml

**Reply by deitch** [reply]
I am not trying to modify how containerd is run, I am quite happy with how it is. I am trying to avoid a fork/exec of a command (i.e. `limactl shell nerdctl ...`) and talk to the containerd socket directly. 

From the "Hard Way" part of the doc, and from my experimenting, it looks like I would need to find the containerd process namespace, construct the path, then map that out to the host?

In my specific lima VM, that is `/proc/3245/root/run/containerd/containerd.sock`, but how would I even know what that would be when writing my lima yaml?

**Reply by jandubois** [reply]
I would try to symlink the socket to a predictable address and then forward from there (untested):

```yaml
provision:
- mode: user
  script: |
    ln -s /proc/$(cat $XDG_RUNTIME_DIR/containerd-rootless/child_pid)/root/run/containerd/containerd.sock $HOME/containerd.sock

portForwards:
- guestSocket: "{{.Home}}/containerd.sock"
  hostSocket: "{{.Home}}/.containerd.sock"
```

If it works, it should forward the socket to `~/.containerd.sock`.

**Reply by afbjorklund** [reply]
>  I am quite happy with how it is

I still don't think that `ctr` or `buildctl` are fit for human consumption, even with my own BuildKit wrapper called `bld`.

For general use, `nerdctl` is much nicer... For minikube's purposes, we made our own wrapper (called `minikube image`)

Then again, I use Docker (Engine).

**Reply by deitch** [reply]
> I still don't think that ctr or buildctl are fit for human consumption, even with my own BuildKit wrapper called bld.

I make no judgement calls. Only that I may have a need to connect to it via library. With docker, I can (and do) use the docker socket to connect. nerdctl is a client, not a daemon, which translates commands to containerd API. So if I want a direct connection, containerd is the way to go.

Either way, this has been very helpful, so thanks all, especially @jandubois

**Reply by jandubois** [reply]
@deitch Please confirm if the symlink idea above actually worked (if you tried it)! I think it should, but computers annoyingly often disagree with me about things like this.

**Reply by deitch** [reply]
It seems to work. I actually set up 2 symlinks, one each for system in `/var/run/containerd.sock` and one for the user in `{{ .Home }}/containerd.sock`, and then forwarded both, just to see if they work:

```yaml
provision:
- mode: system
  script: |
    ln -s /proc/$(cat $XDG_RUNTIME_DIR/containerd-rootless/child_pid)/root/run/containerd/containerd.sock /var/run/containerd.sock
- mode: user
  script: |
    ln -s /proc/$(cat $XDG_RUNTIME_DIR/containerd-rootless/child_pid)/root/run/containerd/containerd.sock $HOME/containerd.sock

portForwards:
- guestSocket: "{{.Home}}/containerd.sock"
  hostSocket: "{{.Home}}/.containerd-user.sock"
- guestSocket: "/var/run/containerd.sock"
  hostSocket: "{{.Home}}/.containerd-system.sock"
```

Both work in principle, i.e. `limactl shell <name> ctr --address <either address> image ls` works, which is good.

I could not test from host because I am on a Mac, no `ctr` client, and I do not have the time right now to compile one using the ctr libraries.

One thing I did stumble across was that this does not work in system:

```yaml
- mode: system
  script: |
    ln -s /proc/$(cat $XDG_RUNTIME_DIR/containerd-rootless/child_pid)/root/run/containerd/containerd.sock /var/run/containerd.sock
```

Because `$XDG_RUNTIME_DIR` is not set for root. How do I get that at the system level?

**Reply by jandubois** [reply]
> I could not test from host because I am on a Mac

That's the part I was wondering about, if forwarding to a symlink is working or not. So if you ever get around to testing, please let us know if it worked.

I don't understand why you need to create a symlink for the system socket; it should already be in a fixed location at `/run/containerd/containerd.sock`.

**Reply by deitch** [reply]
> I don't understand why you need to create a symlink for the system socket; it should already be in a fixed location at /run/containerd/containerd.sock

I don't really. I was just experimenting with setting the symlink as system rather than user.

> That's the part I was wondering about, if forwarding to a symlink is working or not. So if you ever get around to testing, please let us know if it worked.


Will do.

**Reply by deitch** [reply]
First, it actually does work. I built `ctr` on my macOS and ran it:

```sh
$ ctr --address $HOME/.containerd-user.sock image ls
REF TYPE DIGEST SIZE PLATFORMS LABELS
$ ctr --address $HOME/.containerd-user.sock image pull docker.io/library/alpine:3.17
docker.io/library/alpine:3.17:                                                 resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4: done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 4.3 s                                                                 total:   0.0 B (0.0 B/s)
unpacking darwin/arm64/v8 sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4...
ctr: no match for platform in manifest sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4: not found
$ ctr --address $HOME/.containerd-user.sock image ls
ERRO[0000] failed calculating size for image docker.io/library/alpine:3.17  error="content digest sha256:af06af3514c44a964d3b905b498cf6493db8f1cde7c10e078213a89c87308ba0: not found"
REF                           TYPE                                                      DIGEST                                                                  SIZE    PLATFORMS                                                                                LABELS
docker.io/library/alpine:3.17 application/vnd.docker.distribution.manifest.list.v2+json sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4 2.1 KiB linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -
```

There are issues, but I don't think they are relating to the forward-to-symlink.

Second, I found that the provision has an issue if you stop and start the VM. When you do, the child_pid changes, so the symlink is out of date, but continues to exist. Any method for ensuring provisioning runs with every start, not just initial boot?

**Reply by jandubois** [reply]
> Second, I found that the provision has an issue if you stop and start the VM. When you do, the child_pid changes, so the symlink is out of date, but continues to exist. Any method for ensuring provisioning runs with every start, not just initial boot?

The script runs on every boot. I think the problem is just that the destination already exists, so maybe try to always delete it first (again, untested):

```yaml
provision:
- mode: user
  script: |
    rm -f $HOME/containerd.sock
    ln -s /proc/$(cat $XDG_RUNTIME_DIR/containerd-rootless/child_pid)/root/run/containerd/containerd.sock $HOME/containerd.sock
```
