### DISCUSSION TITLE
Documentation for limayaml

### DISCUSSION THREAD

**Discussion by Hefeweizen** [lima-vm/lima#1489] [Ideas]
This comment is about SSH port forwards, specifically, but all of lima.yaml generally.

I started up two k3s instances simultaneously.  They both wanted to port-forward 6443.  However, with this conflict, only one was able to do so.  I resolved this by changing the port-forwarding options on the second VM:
```
portForwards:
- guestPort: 6443
  hostPort: 16443
```
In order to accomplish this, I had to read through limayaml's default.go and limayaml.go.  It'd be nice if this were documented in a better form.

I'm happy to help with this.  However, I wanted to discuss the form this should take.

godoc is the communities preference for technical, api-focused documentation.  I'm not sure if there's something better to create end-user documentation.  A static markdown doc could get this work started, but I'm not sure of the appetite for keeping a separate file up-to-date.

**Comment by afbjorklund** [comment]
Maybe json schema could be used (for documenting yaml), both for validation and visualization?

https://json-schema-everywhere.github.io/yaml

It has some nice tools, like: https://github.com/coveooss/json-schema-for-humans

**Reply by afbjorklund** [reply]
The generic solution turned out to be disappointing, compared to the custom "default.yaml" and `limactl validate`...

![json-schema-lima-yaml](https://user-images.githubusercontent.com/10364051/232237481-1fb4276c-97f1-4d7b-b8f0-1b5d284bb082.png)


```yaml
# CPUs: if you see performance issues, try limiting cpus to 1.
# 🟢 Builtin default: 4
cpus: null

# Memory size
# 🟢 Builtin default: "4GiB"
memory: null

# Disk size
# 🟢 Builtin default: "100GiB"
disk: null

```
