### DISCUSSION TITLE
How to create additional templates?

### DISCUSSION THREAD

**Discussion by lu-zero** [lima-vm/lima#1934] [Q&A]
I'd like to have a Gentoo template but I'm a bit lost on which are the requirements to produce it.

**Comment by afbjorklund** [comment]
You can either just do `edit` inline on the fly, or you can copy the yaml file to a different name.

To create a Gentoo template, you would need to find a "cloud" image that supports `cloud-init`

* https://packages.gentoo.org/packages/app-emulation/cloud-init

Maybe the "OpenStack" images would work ? From [experimental](http://distfiles.gentoo.org/experimental/amd64/openstack/)

----

`limactl start ./examples/experimental/gentoo.yaml`

```yaml
images:
- location: "https://distfiles.gentoo.org/experimental/amd64/openstack/gentoo-openstack-amd64-default-latest.qcow2"
  arch: "x86_64"

# The built-in containerd installer does not support Gentoo currently.
containerd:
  system: false
  user: false
```

* https://github.com/lima-vm/lima/pull/1935 

```console
$ limactl shell gentoo
anders@lima-gentoo ~ $ more /etc/os-release 
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.13"
anders@lima-gentoo ~ $ sudo -sS
lima-gentoo /home/anders.linux # cd
lima-gentoo ~ # emerge-webrsync
```
