### DISCUSSION TITLE
Running a VM that persists data on macOS

### DISCUSSION THREAD

**Discussion by moenodedev** [lima-vm/lima#2359] [Q&A] [answered]
I would like to run a vz/virtiofs alpine VM on macOS that persists installed packages, system configuration files, and dotfiles. Is this possible with [alpine-lima](https://github.com/lima-vm/alpine-lima) or do I need to create my own custom image?

**Comment by jandubois** [comment, marked as answer]
I've created an `alpine-image` template in #2360 that uses the Alpine cloud images instead of our alpine-lima ISO, so everything will be persisted in the VM automatically.

All it needed was a small change to make sure `sudo` is installed, as the cloud images only come with `doas`.

Please check it out and let us know how it works for you!

**Reply by moenodedev** [reply]
Thank you! I'll try it out

**Reply by moenodedev** [reply]
It works! Changes are persisted.

With this config and ssh command I get brought into my preferred shell and home directory:

```yaml
disk: "15GiB"

mountType: "virtiofs"
mounts:
  - location: "~/Lima/development/home"
    mountPoint: "/home/development"
    writable: true
  - location: "/tmp/lima"
    writable: true

vmType: "vz"
os: "Linux"
arch: "aarch64"

audio:
  device: "vz"
video:
  display: "none"
networks:
  - vzNAT: true
ssh:
  localPort: 54203
  loadDotSSHPubKeys: false
  forwardAgent: false
  forwardX11: false
  forwardX11Trusted: false

images:
  - location: "https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/cloud/nocloud_alpine-3.19.1-aarch64-uefi-cloudinit-r0.qcow2"
    digest: "sha512:d5e69cff0ecb0fd3850bd78f56f66131115934df27b2373c35a85a74b9def52822134dd43f90b4fabe239fdd4452026cb45f1c8f0b36a43af69335a26f0959b5"
    arch: "aarch64"
containerd:
  system: false
  user: false
```

```sh
ssh \
  -F ~/.lima/development/ssh.config \
  -o PubkeyAuthentication=no \
  -o PreferredAuthentications=password \
  -o RequestTTY=force \
  lima-development \
  -- "export HOME=/home/$USER ; export SHELL=/bin/zsh ; zsh -l"
```
