### DISCUSSION TITLE
Support script files in addition to inline scripts for provisioners.

### DISCUSSION THREAD

**Discussion by Ranjandas** [lima-vm/lima#2441] [Ideas]
Can the provisioners point to script files as an alternate option to inline scripts? This will be very useful when we have a bunch of templates that share many script blocks in common but set up unique environments. This will have the following benefits in my view:

1. It will be easy to maintain the templates, and we won't have to worry about the inline scripts breaking YAML.
2. It will allow the reuse of the scripts rather than copying and pasting scripts from one template to another.
3. Maintaining shell scripts outside YAML (in their own files) would allow better quality control of the scripts (e.g., running ShellCheck against the scripts, etc.).

Something similar to the following:

```
provision:
  - mode: system
    script:
      path: ./scripts/001-bootstrap.sh
```

Thanks in advance. 🙏

**Comment by afbjorklund** [comment]
It will need a slightly different syntax, since "script" is the content of the script.

Like:
```yaml
provision:
  - mode: system
    script: ""
    path: ./scripts/001-bootstrap.sh
```

The main complexity is that the script path needs to be available in the instance.

With the Ansible playbooks, they are copied over by `ansible-playbook` command

----

Some templates **are** using external scripts today, but then they are downloaded:

```
    curl -fsSL https://get.docker.com | sh
```

```
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644" sh -
```

Another approach is to template the creation of the yaml files, something like jinja2.
