### DISCUSSION TITLE
Snakeware - interesting graphical distribution

### DISCUSSION THREAD

**Discussion by afbjorklund** [lima-vm/lima#2459] [Show and tell]
https://github.com/joshiemoore/snakeware

"snakeware is a free Linux distro with a Python userspace inspired by the Commodore 64."

It doesn't have sshd (so eventually it times out, even in --plain mode, but it does have a UI)

```yaml
arch: x86_64
memory: 2GiB

images:
- location: https://github.com/joshiemoore/snakeware/releases/download/v0.0.6/snakeware_x86-64_0-0-6.iso
  arch: "x86_64"
firmware:
  legacyBIOS: true

audio:
  device: pa
video:
  display: default
```

There is no particular reason this would be "better" than [load81](https://github.com/antirez/load81), but still. It looked interesting.

It would be possible to rebuild for aarch64, or to change the bootloader from BIOS to UEFI.

----

* https://github.com/lima-vm/lima/pull/2456 - instead of using "pa"

* https://github.com/lima-vm/lima/discussions/1002

![lima-snakeware-ui](https://github.com/lima-vm/lima/assets/10364051/78157321-03e3-41de-98b4-2de8438b2684)

![lima-snakeware-wm](https://github.com/lima-vm/lima/assets/10364051/e13b1810-a65d-4c2b-877f-d65cd4051a19)
