### DISCUSSION TITLE
Networking options on Linux Hosts (similar to socket_vmnet)

### DISCUSSION THREAD

**Discussion by Ranjandas** [lima-vm/lima#2499] [Q&A]
What are the networking options available on Lima on Linux Hosts. Is it possible to have networking similar to that of `socket_vmnet` on macOS? When I tried using the `bridged` networking mode it errors.

```
 limactl start template://fedora --network lima:bridged --plain
? Creating an instance "fedora" Proceed with the current configuration
FATA[0000] the YAML is invalid, saved the buffer as "lima.REJECTED.yaml": field `networks[0].lima` is only supported on macOS right now 
```

**Comment by why168** [comment]
eg
```yaml
networks:
  # Lima can manage the socket_vmnet daemon for networks defined in $LIMA_HOME/_config/networks.yaml automatically.
  # The socket_vmnet binary must be installed into a secure location only alterable by the admin.
  # $LIMA_HOME/_config/networks.yaml. Supported network types are "host", "shared", or "bridged".
  - lima: bridged
    # Interface "lima0": shared mode  (IP is assigned by macOS's bootpd)
    interface: "lima0"
  - lima: shared
    # Interface "lima1": bridged mode (IP is assigned by a DHCP server on the physical network)
    interface: "lima1"
```
