### DISCUSSION TITLE
Help understanding "guestPortRange" and "hostPortRange" in instance YAML template file

### DISCUSSION THREAD

**Discussion by amansharma-mo** [lima-vm/lima#2653] [Q&A] [answered]
I added the below to the `debian-12.yaml` template file, but when I run `limactl start debian-12.yaml`, I am not seeing any logs related to these ports being forwarded. Perhaps I am not understanding the comments in `default.yaml` template file for `portForwards` properly. Is this not the right way to forward these specified ports from host to guest? 

### System Info:
Apple M1
Sonoma 14.7
limactl version 0.23.2

EDIT: Template file
```yaml
# This template requires Lima v0.7.0 or later
images:
# Try to use release-yyyyMMdd image if available. Note that release-yyyyMMdd will be removed after several months.
- location: "https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-amd64-20240717-1811.qcow2"
  arch: "x86_64"
  digest: "sha512:0f0075d53749dba4c9825e606899360626bb20ac6bab3dbdeff40041b051d203eb1a56e68d377c9fac0187faa0aea77fd543ef4a883fff2304eac252cce01b44"
- location: "https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-arm64-20240717-1811.qcow2"
  arch: "aarch64"
  digest: "sha512:a68fe32c459d6d33cd8f6798fe7e2278d32add2b9506f4a6c434328a0a9cd176e532a93d0184173720023db5edfd93061082fadcb91bb3e95988564c63f139a6"
# Fallback to the latest release image.
# Hint: run `limactl prune` to invalidate the cache
- location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
  arch: "x86_64"
- location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2"
  arch: "aarch64"

cpus: 2
memory: 1GiB
disk: 20G
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
portForwards:
- guestPortRange: [10279, 10281]
  hostPortRange: [10279, 10281]
```
