### DISCUSSION TITLE
With vzNAT  - how can I force the lima0 ip address [ the one available from host ] ?

### DISCUSSION THREAD

**Discussion by cgimenez** [lima-vm/lima#2696] [Q&A]
Hi all and cudos for the work done on Lima !

`limactl create --name vm1 ./myconfig.yaml # see below`

the lima0 interface vm IP address is : 192.168.64.X

- I can ping / connect from host to guest w/o problem
- But how can I force this address when the vm is created ?
- when creating / destroying virtual machines X is always incremented and never reused (and I've not found where this counter is stored)

So, I would like to create a VM reusing the same IP used by the last destroyed vm

Disclaimer : I discovered lima this morning, so total noob ;-)

Note : I'm using the macports version of Lima

```YAML
# This template requires Lima v0.7.0 or later
# https://github.com/lima-vm/lima/blob/master/examples/default.yaml
# limactl create --tty=false --name "vm3" ./config.yaml
images:
  # Try to use release-yyyyMMdd image if available. Note that release-yyyyMMdd will be removed after several months.
  - location: "https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-amd64-20240717-1811.qcow2"
    arch: "x86_64"
    digest: "sha512:0f0075d53749dba4c9825e606899360626bb20ac6bab3dbdeff40041b051d203eb1a56e68d377c9fac0187faa0aea77fd543ef4a883fff2304eac252cce01b44"
  - location: "https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-arm64-20240717-1811.qcow2"
    arch: "aarch64"
    digest: "sha512:a68fe32c459d6d33cd8f6798fe7e2278d32add2b9506f4a6c434328a0a9cd176e532a93d0184173720023db5edfd93061082fadcb91bb3e95988564c63f139a6"
  # Fallback to the latest release image.
  # Hint: run `limactl prune` to invalidate the cache
  - location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
    arch: "x86_64"
  - location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2"
    arch: "aarch64"
vmType: "vz"
cpus: 2
memory: 8Gib
disk: 60Gib
networks:
  - vzNAT: true

hostResolver:
  enabled: true

mounts:
  - location: "~/lima_shared"
    writable: false
mountType: "virtiofs"
```
