### DISCUSSION TITLE
Host's memory consumption is x1.6 of VM

### DISCUSSION THREAD

**Discussion by frkd-dev** [lima-vm/lima#2843] [General]
I'm wondering why I'm seeing such an enormous real memory consumption for the VM?

<img width="1036" alt="Screenshot" src="https://github.com/user-attachments/assets/1f89d32f-118e-46d2-971e-24302b292af6">

I run VM on M2 Pro with the following config:

```yml
cpus: 8
memory: 6GiB
mountType: virtiofs
vmType: vz
rosetta:
  enabled: true
  binfmt: true
```

The VM runs the Alpine arm64 with Docker to build C++ projects. I can't explain why real memory exceeds 1.6 time of the VM. Considering compressed memory, a total amount is above 10GB for the 6 GB VM. It's a total waste of memory.
