### DISCUSSION TITLE
Are there any way to pass host environment variables to container?

### DISCUSSION THREAD

**Discussion by ryutaro-asada** [lima-vm/lima#2919] [Q&A]
Are there any way to pass host environment variables to container?

- docker-compose.yml

```
services:
  terraform:
    image: hashicorp/terraform:1.2.9
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: env
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
```

- command

```
$ lima nerdctl compose up -d
$ lima nerdctl logs infra-terraform-1                                                                                                                                                                                                                                                                           feature/latest_udater_for_episode * ] 6:10 PM
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
HOSTNAME=terraform
HOME=/root
```

Probably because the host environment variable cannot be passed to lima vm.
