### DISCUSSION TITLE
Proxmox Stuck on Grub Bootloader, How do I connect and install via terminal?

### DISCUSSION THREAD

**Discussion by shawlz** [lima-vm/lima#3077] [Q&A] [answered]
Hello, I'm new to using lima to run VM on MacOSX so apologies for the noob question. 

The VM starts, but it's stuck at the grub bootloader, so I can't connect via SSH. 

How do I do either of the following, please? 
- Connect via Serial Port to kickstart the installation process? 
- Connect via Display to VM? 
- Any other ideas on how to run Proxmox

`proxmox.yaml` 
```
arch: "x86_64"
images:
  - location: "file:///XXXXXXXproxmox-ve_8.3-1.iso" # Replace with the absolute path to your ISO
    arch: "x86_64"
    type: iso
cpu: 2
memory: "4GiB"
disk: "40GiB"
ssh:
  localPort: 60022
mounts:
  - location: "~"
    writable: false
boot:
  kernelCmdline: "console=ttyS0"
provision:
  - mode: system
    script: |
      #!/bin/bash
      echo "Custom VM provisioning"
```

`serial.log` 
```
3h3h3hBdsDxe: failed to load Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x1,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0002 "UEFI QEMU DVD-ROM QM00001 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0002 "UEFI QEMU DVD-ROM QM00001 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)
Welcome to GRUB!

^Merror: file `/EFI/' not found.
^Merror: no such device: /.disk/info.
^Merror: no such device: /.disk/mini-info.
^MGNU GRUB  version 2.06-13+pmx2

^M+----------------------------------------------------------------------------+||||||||||||||||||||||||+----------------------------------------------------------------------------+     Use the ^ and v keys to select which entry is highlighted.
^M      Press enter to boot the selected OS, `e' to edit the commands
^M      before booting or `c' for a command-line.                            *Install Proxmox VE (Graphical)                                              Install Proxmox VE (Terminal UI)                                            Install Proxmox VE (Terminal UI, Serial Console)                            Advanced Options
```

*System Information*
`system_profiler SPSoftwareDataType SPHardwareDataType`
```
Software:
    System Software Overview:
      System Version: macOS 14.6.1 (23G93)
      Kernel Version: Darwin 23.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

Hardware:

    Hardware Overview:
      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Model Number: Z14W00105LL/A
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 10151.140.19
      OS Loader Version: 10151.140.19
```
