### DISCUSSION TITLE
How to make UDP forwarding work for Graphite?

### DISCUSSION THREAD

**Discussion by brandonros** [lima-vm/lima#3178] [Q&A] [answered]
With k3s running in Debian:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: graphite
  namespace: kube-system
spec:
  repo: https://kiwigrid.github.io
  chart: graphite
  targetNamespace: monitoring
  valuesContent: |-
    image:
      repository: graphiteapp/graphite-statsd
      tag: 1.1.10-5
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 8080

    persistence:
      enabled: true
      size: 10Gi

    ingress:
      enabled: false

    timeZone: UTC

    statsd:
      interface: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: graphite-statsd
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: statsd
      port: 8125
      targetPort: 8125
      nodePort: 30000
      protocol: UDP
  selector:
    app.kubernetes.io/name: graphite
    app.kubernetes.io/instance: graphite
```

You will not be able to reach port 30000 from the host as per https://github.com/lima-vm/lima/issues/3152
