### DISCUSSION TITLE
Alpine docker-host challenge

### DISCUSSION THREAD

**Discussion by krzysztof-abramowicz** [lima-vm/lima#3277] [Q&A]
I chose Lima to build my custom, light & fast Docker Desktop alternative with Alpine Linux as my docker-host VM’s OS (vm-host: macOS 15.3 @ M2). It seemed to be a pleasing warmup before my in-depth Docker learning and further experiments. Unfortunately, I encountered several irritating problems:

1. Starting an Alpine Linux machine hangs on `[hostagent] Waiting for the essential requirement 2 of 4: "user session is ready for ssh"` (for QUEMU, “2 of 2” for VZ). Despite of the error, machine becomes available, but it ruins the user experience. _My fix: Adding a provisioning script (`provision:` section) seems to help, but why?_
2. The created user does not belong to the `wheel` group by default, so one cannot execute commands with elevated privileges. _My fix: the group membership may be added manually in the provisioning script._
3. The created user doesn’t have a password and this cannot be changed with `passwd` as there’s no password. Minor issue. _My fix: `sudo passwd <user>` does not prompt for the current, non-existent  password._
4. The created user does not belong to the `docker` group, thus cannot connect to the docker daemon (access it's socket). This cannot be fixed by the provisioning script as by its execution the user session has already been started; the association, although visible in `/etc/group`, doesn’t take effect. _Manual fix: `sudo reboot`_
5. The user-space x86_64 emulation doesn’t work. I’m getting `exec format error` on both QEMU and VZ machine. _My fix: The `qemu-x86_64` and `qemu-openrc` packages may be installed, and the `qemu-binfmt` service started manually (thus the binary format is registered in the kernel)._ 
6. The Rosetta share doesn’t seem to be exposed to the VM. I’d try to mount it manually, but I can’t see other devices than `virtio2` (`vda`, local mounts) and `virtio3` (`vdb`, cidata). How can I check if Lima has exposed the Rosetta share to the VM correctly? May I choose to use Rosetta or QUEMU as `amd64` handler through the configuration?
7. The log item `tcpproxy: for incoming conn 127.0.0.1:50635, error dialing "192.168.5.15:22": connect tcp 192.168.5.15:22: connection was refused` bypasses JSON formatting, thus the `ha.stderr.log` cannot by parsed with `jq` without additional filtering. Small thing, but annoying.
8. There are plenty of `Stopping udp proxy ` entries in the log, and they take up most of it over time! Does it have to happen so frequently? And what's the reason for it?

As you can see, I found a way to finally got close to my dream result, but I believe it could be achieved much easier. Maybe I haven't understand some design assumptions, or maybe a few things could be improved in Lima? I'm even eager to contribute some solutions myself, but I have to become a successful power user first :)

I'm also aware of the fact, that there are docker-enabled VM templates build on Ubuntu, but I got used to using Alpine in the cloud and I'd like to experiment with it on my desktop as well. Besides, It's Linux – everything is possible! Right?

I will be grateful for any tips, improvements or suggestions for my possible contributions.

My current VM configuration:
```
images:
- location: "https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/cloud/nocloud_alpine-3.21.2-x86_64-uefi-cloudinit-r0.qcow2"
  arch: "x86_64"
  digest: "sha512:1aaf22b4a584e69e228e6aa38a295159c0143d9ccebe7ad4928e92b414714066af3bfe5f9e0ca4d4d64a70ca9fea09033af90258a6f2344130d70b660151127a"
- location: "https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/cloud/nocloud_alpine-3.21.2-aarch64-uefi-cloudinit-r0.qcow2"
  arch: "aarch64"
  digest: "sha512:08d340126b222abae651a20aa63c3ee3dc601d703de7879d2a6bc1fe82a3664d058a2c55ad0cf8a874327f7535e3af8a9384ce438217d6f32200cad1462a5b32"

vmType: vz
rosetta:
  enabled: true
  binfmt: true

mountType: virtiofs
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true

containerd:
  system: false
  user: false

provision:
- mode: system
  script: |
    # 1. sudo  
    apk add sudo
    adduser krab wheel
    # 2. Docker daemon
    apk add docker
    adduser krab docker
    service docker start
    rc-update add docker default
    # 3. QEMU user-space amd64 emulation
    apk add qemu-x86_64 qemu-openrc
    rc-service qemu-binfmt start
    rc-update add qemu-binfmt default

portForwards:
- guestSocket: "/var/run/docker.sock"
  hostSocket: "{{.Dir}}/sock/docker.sock"
```
