### DISCUSSION TITLE
External variables file (basedOn)

### DISCUSSION THREAD

**Discussion by etho201** [lima-vm/lima#3400] [General]
Is it possible to define the parameters from an external file (for example, `variables.yaml`) in order to keep custom/sensitive parameters out of the template files?

I asked this [same question](https://github.com/lima-vm/lima/pull/2570#issuecomment-2491361411) back in November and was informed that this will be possible when the implementation of [basedOn](https://github.com/lima-vm/lima/discussions/2520#discussioncomment-10193570) is complete. That is exactly what I'm looking for. Any status updates or estimates as to when this will be available?

**Comment by jandubois** [comment]
I think it is (but the key is now called `base` instead of `basedOn`). Can you provide a concrete example of how you specify and use the parameters? Then I could show you how you could implement that using `base`.

**Comment by etho201** [comment]
For example, if I have a template called `oraclelinux9.yaml`:

```yaml
- location: "https://yum.oracle.com/templates/OracleLinux/OL9/u5/x86_64/OL9U5_x86_64-kvm-b253.qcow2"
  arch: "x86_64"
  digest: "sha256:3b00bbbefc8e78dd28d9f538834fb9e2a03d5ccdc2cadf2ffd0036c0a8f02021"
- location: "https://yum.oracle.com/templates/OracleLinux/OL9/u5/aarch64/OL9U5_aarch64-kvm-cloud-b117.qcow2"
  arch: "aarch64"
  digest: "sha256:6b62b633eb66cd1769015c25699d4d5f15c41c8fe5ef6ec3e81f0f2d5ed9e4d4"
mountTypesUnsupported: ["9p"]
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
firmware:
  # Oracle Linux 9 still requires legacyBIOS, while AlmaLinux 9 and Rocky Linux 9 do not.
  legacyBIOS: true

provision:
  # `system` is executed with the root privilege
  - mode: system
    script: |
      #!/bin/bash
      echo "Hello $secret" > test.txt
```

And I have a `variables.yaml` file like the following:

```yaml
base: [oraclelinux9.yaml]

param:
  secret: password123
```

If I type:

```bash
limactl start variables.yaml
```

I am getting the following error: `error="[1:1] unknown field \"base\"\n>  1 | base: oraclelinux9.yaml\n`

I have limactl version 1.0.7

**Reply by etho201** [reply]
In that example, I would want "Hello password123" printed to the `test.txt` file. Also, it's been a while since I looked at this, and can't remember if it needs to be:

```yaml
param:
  secret: password123
```

or 

```yaml
env:
  secret: password123
```

**Reply by jandubois** [reply]
You need to use the [v1.1.0-alpha.0](https://github.com/lima-vm/lima/releases/tag/v1.1.0-alpha.0) pre-release to get the support for `base`. It is not yet available in the regular release.

**Reply by jandubois** [reply]
> can't remember if it needs to be [`param` or `env`]

Either should work, but if you use `param` then the script needs to use `$PARAM_secret`.

**Reply by jandubois** [reply]
> ```yaml
> base: [oraclelinux9.yaml]
> ```

If you have just a single base template, then you can also specify it like this:

```yaml
base: oraclelinux9.yaml
```

**Comment by etho201** [comment]
@jandubois -- the new `base` functionality works great! I realize it's an experimental feature and subject to change, so I'll monitor the documentation and release notes to be aware of any changes.

I was able to simplify my example with:

`variables.yaml`
```yaml
env:
  secret: password123
```

`oraclelinux9.yaml`
```yaml
base: [template://oraclelinux-9, variables.yaml]

provision:
  - mode: system
    script: |
      #!/bin/bash
      echo "Hello $secret" > /tmp/test.txt
```

I think I can work with this. Thank you for all your hard work!
