### DISCUSSION TITLE
What is the best way to copy a file during a provision script?

### DISCUSSION THREAD

**Discussion by etho201** [lima-vm/lima#3402] [General]
Let's say I have a directory with my project files:

```
.
├── README.md
├── files
│   ├── Dockerfile
│   └── local-yum.repo
├── oraclelinux9.yaml
└── variables.yaml
```

In my oraclelinux9.yaml file, I have a provision section where I want to copy the `files/local-yum.repo` file to some other directory in the VM.

For example:

```yaml
provision:
  - mode: system
    script: |
      #!/bin/bash
      mkdir -p /var/www/html/yum
      cp files/local-yum.repo /var/www/html/yum/
```

In addition to specifying a relative path, I tried specifying `cp $LIMA_WORKDIR/files/local-yum.repo /var/www/html/yum/` but that doesn't work. I also tried adding a mount so I could predict where in the VM it will show up but that doesn't seem to be working either. What is the best way to do this?

**Comment by jandubois** [comment]
You should be able to do this with a "data" provisioning file. Something like:

```yaml
provision:
- mode: data
  file: files/local-yum.repo
  path: /var/www/html/yum/local-yum.repo
```

This also requires Lima 1.1.0-alpha.0 or later.

**Reply by jandubois** [reply]
Note that the file will be embedded in `lima.yaml` when the instance is created. It will not be updated when you stop and restart the instance.

**Reply by etho201** [reply]
Thank you @jandubois. That will work for me most of the time.

What about when/if I need a folder with several files (or if the file was a binary of sorts)? Then would it be better to specify a mount? I tried this earlier but had a strange memory related error and was unable to execute a shell into the VM. I can show you the details of the error tomorrow.

**Reply by jandubois** [reply]
> What about when/if I need a folder with several files (or if the file was a binary of sorts)?

Yes, data provisioning needs to specify each file individually.

Binary files will work as long as they are short. This can probably be fixed to work with long files too (#3403), but embedding long binary files in YAML (e.g. base64 encoded) will become unwieldy quickly.

```console
❯ printf "\x00\x01" > binary.data

❯ hexdump -C binary.data
00000000  00 01                                             |..|
00000002

❯ cat tmpl.yaml
base: template://alpine
provision:
- mode: data
  file: binary.data
  path: /tmp/binary.data

❯ limactl tmpl copy --embed tmpl.yaml -
WARN[0000] `provision[*].file` and `probes[*].file` are experimental
base: template://alpine
provision:
- mode: data
  content: \x00\x01
  path: /tmp/binary.data
```

**Reply by etho201** [reply]
Very cool that binary files can be passed through YAML as well. Thank you.

By the way, I was able to get the mount stuff working... the problem I faced yesterday is because I was using `1.1.0-alpha.0` to start the VM, but was using `1.0.7` to connect to the shell since that is what's in my environment path.

```yaml
mounts:
  - location: files/
    mountPoint: /tmp/files
    writable: true
```

The error was `WARN[0000] instance "ksplice-offline" has errors         errors="[field `mounts[2].location` must be an absolute path, got \"files/\"]"` but I guess that's just something that isn't supported in `1.0.7`.
