### DISCUSSION TITLE
Network access from host to debian (vz)

### DISCUSSION THREAD

**Discussion by mshlain** [lima-vm/lima#3414] [Q&A] [answered]
Hi team!
I'm struggling to make my micork8s application accessible from host.

my template:
```
vmType: "vz"
rosetta:
  enabled: true
  binfmt: true

images:
  - location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2"
    arch: "aarch64"
mountTypesUnsupported: ["9p"]
mounts:
  - location: "~"
  - location: "/tmp/lima"
    writable: true

cpus: 8
memory: 16GiB
disk: 35GiB
```

the application is accessible locally when ssh inside default instance

```
> hostname -I
192.168.5.15 10.4.0.1 10.1.74.0 10.1.74.1

> curl -k 192.168.5.15 | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   146  100   146    0     0    99k      0 --:--:-- --:--:-- --:--:--  142k
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

but nothing comes when trying to curl from my host (mac) with 'curl -k 192.168.5.15':
```
curl: (28) Failed to connect to 192.168.5.15 port 80 after 75002 ms: Couldn't connect to server
```

ima --version
limactl version 1.0.7
