### DISCUSSION TITLE
How to specify memory resources in lima/nerdctl

### DISCUSSION THREAD

**Discussion by doberkofler** [lima-vm/lima#453] [Q&A] [answered]
I'm trying to a run an Oracle  Database in a Docker image in a lima environment on macOS and get a lot of errors related to the shm volume.

```bash
lima nerdctl run --detach --name="oracledb" --network="oraclenet" --memory="4g" --publish="1521:1521" --volume="/dev/shm" --tmpfs="/dev/shm:rw,exec,size=1g" qualiant/database
```

I did not find documentation that explains how memory resources are allocated in lima and wanted to ask a few specific questions:

1) Docker Desktop for macOS have an overall limit for memory consumption on the container. Where can I find this in lima?
2) `nerdctl` support the `--memory` option but how does this relate to lima? Is it guaranteed that the container gets 4g when using the `--memory="4g"` flag independently from lima?

Thank you!

**Comment by afbjorklund** [comment, marked as answer]
> Docker Desktop for macOS have an overall limit for memory consumption on the container. Where can I find this in lima?

When you started the virtual machine, there was a YAML file to edit. It included fields like "cpus" and memory"

```
? Creating an instance "default"  [Use arrows to move, type to filter]
> Proceed with the default configuration
  Open an editor to override the configuration
  Exit
```

After it has been started, it is saved as ~/.lima/default/lima.yaml (or similar, for other instances than "default")

```yaml
# CPUs: if you see performance issues, try limiting cpus to 1.
# Default: 4
cpus: 4

# Memory size
# Default: "4GiB"
memory: "4GiB"

# Disk size
# Default: "100GiB"
disk: "100GiB"
```

You need to `restart` it for changes to take effect. View changes with `list`.

Resizing the disk image is be a bit trickier, and requires manual commands.
