### DISCUSSION TITLE
mkdir /path/lima/wks: read-only file system

### DISCUSSION THREAD

**Discussion by cmoulliard** [lima-vm/lima#601] [Q&A]
## Issue

I created successfully a docker VM using the command 

```
limactl start https://raw.githubusercontent.com/afbjorklund/lima/master/examples/docker.yaml
...
INFO[0165] READY. Run `limactl shell docker` to open the shell. 
INFO[0165] To run `docker` on the host (assumes docker-cli is installed): 
INFO[0165] $ export DOCKER_HOST=unix:///Users/cmoullia/.lima/docker/sock/docker.sock 
INFO[0165] $ docker ...    
```

but when I launch a script able to install kind kubernetes then I got as response 
```
docker: Error response from daemon: error while creating mount source path '/Users/cmoullia/code/snowdrop/infra-jobs-productization/k8s-infra/lima/wks': 
mkdir /Users/cmoullia/code/snowdrop/infra-jobs-productization/k8s-infra/lima/wks: read-only file system.
```

If I move under `/tmp/lima`, I got a permission denied `docker: Error response from daemon: error while creating mount source path '/tmp/lima/wks': chown /tmp/lima/wks: permission denied.`

## Versions

Lima: `limactl version 0.8.1`
OS: Darwin MacBook-Pro 20.6.0

**Comment by afbjorklund** [comment]
The home directory is read-only, by default.

```yaml
# Expose host directories to the guest, the mount point might be accessible from all UIDs in the guest
# Default: null
mounts:
- location: "~"
  # CAUTION: `writable` SHOULD be false for the home directory.
  # Setting `writable` to true is possible, but untested and dangerous.
  # Default: false
  writable: null
  sshfs:
    # Enabling the SSHFS cache will increase performance of the mounted filesystem, at
    # the cost of potentially not reflecting changes made on the host in a timely manner.
    # Default: false
    cache: null
    # SSHFS has an optional flag called 'follow_symlinks'. This allows mounts
    # to be properly resolved in the guest os and allow for access to the
    # contents of the symlink. As a result, symlinked files & folders on the Host
    # system will look and feel like regular files directories in the Guest OS.
    # Default: false
    followSymlinks: null
- location: "/tmp/lima"
  writable: true
  sshfs:
    followSymlinks: null
```

* https://github.com/lima-vm/lima/discussions/550

The mounts were copied from docker.yaml

The other directory should work, possibly some issue when running docker as root ?

I _thought_ that fuse.conf had `user_allow_other`, but maybe it also needs `allow_other`.
