### DISCUSSION TITLE
Pass in USB drive with linux filesystem?

### DISCUSSION THREAD

**Discussion by hemna** [lima-vm/lima#618] [Q&A]
How can I pass in a usb drive into the guest OS with lima?   I have a microsd formatted for linux and would like to mount it in my lima started vm.

**Comment by AkihiroSuda** [comment]
This yaml should work:

```yaml
images:
- location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-arm64.img"
  arch: "aarch64"
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
- location: "/Volumes"
```
