### DISCUSSION TITLE
What is the path to the podman socket in the host

### DISCUSSION THREAD

**Discussion by iongion** [lima-vm/lima#624] [Q&A] [answered]
I am trying to communicate with the podman api from a client running in the host.

On podman running in native linux I start the api using 

`podman system service --time=0 unix:///tmp/podman.sock --log-level=debug`

Then http clients over unix socket can access the api.

**Comment by afbjorklund** [comment, marked as answer]
When starting "podman.yaml", it will print out the podman.sock location.

```
To run `podman` on the host (assumes podman-remote is installed):
$ export CONTAINER_HOST=unix:///home/anders/.lima/podman/sock/podman.sock
$ podman --remote ...
```

Normally it is under "sock/podman.sock", in the lima instance directory.

```yaml
portForwards:
- guestSocket: "/run/user/{{.UID}}/podman/podman.sock"
  hostSocket: "{{.Dir}}/sock/podman.sock"
```

It is started with `systemctl --user enable --now podman.socket` in the VM.

https://github.com/containers/podman/blob/main/docs/tutorials/remote_client.md
