### DISCUSSION TITLE
What should be put into /private/etc/sudoers.d/lima used by $LIMA_HOME/_config/networks.yaml?

### DISCUSSION THREAD

**Discussion by andy-avx** [lima-vm/lima#702] [Q&A] [answered]
System: Apple M1 Max, macOS Monterey
Lima 0.8.3

I'm trying to configure vde_vmnet in managed mode as described at https://github.com/lima-vm/lima/blob/master/docs/network.md#managed-vmnet-networks-via-vde_vmnet

I have vde_vmnet compiled/loaded in launchd no problem. It works in unmanaged mode, but for managed mode it seems we need to provide a path to `sudoers` file in `$LIMA_HOME/_config/networks.yaml`. The default value there is `/private/etc/sudoers.d/lima` but this file does not exist.

Question: how should this sudoers file look like and are there examples for it?

I tried:
- Referencing /private/etc/sudoers
- Using the one from vde_vmnet project: https://github.com/lima-vm/vde_vmnet/blob/master/etc_sudoers.d/vde_vmnet

In both cases `limactl start` gives me an error: `sudoers file <path> is out of sync and must be regenerated`.

P.S.
$LIMA_HOME/_config/networks.yaml:
```
paths:
  vdeSwitch: /opt/vde/bin/vde_switch
  vdeVMNet: /opt/vde/bin/vde_vmnet
  varRun: /private/var/run/lima
  sudoers: /private/etc/sudoers.d/lima       <<<<<<<<<<<<<<
```

Please advise
