### DISCUSSION TITLE
Any help with CentOS8-Stream?

### DISCUSSION THREAD

**Discussion by ajaya** [lima-vm/lima#897] [Q&A] [answered]
Folks

Just a basic config from centos.  with cloud image https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2

I am on Mac x86 and trying CentOS x86.  Serial log shows trying to go to PXE and HTTP boot and then land in grub console.

How to start debugging this?

AJ

**Comment by afbjorklund** [comment]
CentOS Stream-8 worked OK on Linux (for both arch, on amd64 host), and previously CentOS Stream-9 was also working OK

Enabling the QEMU display might give some insights, you might also try with different versions (6.2.0 vs 7.0.0) and debug flags

**Reply by afbjorklund** [reply]
You might also want to try with one of the released RHEL clones, as in not this beta version (Stream) - but a release like 8.5 or 8.6

https://github.com/lima-vm/lima/blob/master/examples/almalinux.yaml
https://github.com/lima-vm/lima/blob/master/examples/rocky.yaml
https://github.com/lima-vm/lima/blob/master/examples/oraclelinux.yaml

Or Fedora.

**Comment by afbjorklund** [comment, marked as answer]
Here is example yaml:

```yaml
# This example requires Lima v0.8.3 or later.

images:
- location: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2
  arch: "x86_64"
  digest: "sha256:a25560ab39e10594ee7a4a1dadcba7bf303b7c3c41559b4a7fc3c522540a6672"
- location: https://cloud.centos.org/centos/8-stream/aarch64/images/CentOS-Stream-GenericCloud-8-20220125.1.aarch64.qcow2
  arch: "aarch64"
  digest: "sha256:d973991085db0ca8373e1d9948440213cdc76b6acf8f17aa2aed2163c1347cbc"
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
firmware:
  legacyBIOS: true
cpuType:
  # Workaround for "vmx_write_mem: mmu_gva_to_gpa XXXXXXXXXXXXXXXX failed" on Intel Mac
  # https://bugs.launchpad.net/qemu/+bug/1838390
  x86_64: "Haswell-v4"
```

Maybe you were missing the CPU type workaround ?
