### DISCUSSION TITLE
Support for Virtualization.framework

### DISCUSSION THREAD

**Discussion by balajiv113** [lima-vm/lima#923] [Ideas]
This discussion is to come up with a plan for implementing drivers in lima and also provide support for Virtualization.framework in macOS.

## Requirements
- Support for Virtualization must be optional
- Only available on macOS
- Same model should be extensible for other drivers in future

## Support for different drivers
The base idea is to support different drivers implementations and pick a driver accordingly based on the VM configuration.

## Idea - Driver code will be part of lima
The idea is to have different drivers as part of lima itself (No separate binaries for drivers)

- **qemu** - Will be the default driver
- **vz** - available only for macOS

### Driver - qemu
All the current features/codeflows will stay the same, we will only refactor code to support multiple driver model.

**Note** - There should be no change in configuration file as well

### Driver - vz
The main complication here will be Virtualization.framework is available only after macOS 11. Also features we will use (EFILoader) are available only as part of macOS 13.
But we should support older versions of macOS as well.

To overcome this complications, I have came up with 2 integration options

#### Integration - Directly use vz go-binding in lima
In this model, lima will directly depend on code-hex/vz.git go binding for mac virtualization API. And the vz driver will create VM using those go-binding.

**Pros**

- Better/Deep integration with virtualization API
- We can make use of VZ features like vsock, vmStateChange etc

**Cons**

- We should plan for not building this driver/use no-op if lower version of macOS is used. One way to do is maybe to use custom build tag and set it during build based on current building os version

#### Integration - Cmd line utility for vz
In this model, We will develop a cmd line tool like https://github.com/code-ready/vfkit and the driver will simply spawn a child process like in qemu driver

**Pros**

- Easily ignore driver at runtime base on current running version. The cli is already built, and we will simply download when needed.

**Cons**

- Hard to provide a deep integration / more work will be needed on creating the cli tool

### Configuration changes
I tried to come up with a basic configuration model for driver based solution.
The goal I had in mind was to accommodate our current configuration for new driver as well.
This way, we can reuse configuration for different drivers as well.

```yaml
driver: "vz" //We should maybe allow this to be given during initial start command

images:
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "x86_64 iso file"
    arch: "x86_64"
    driver: "vz"
  - location: "aarch64 iso file"
    arch: "aarch64"
    driver: "vz"

mounts:
  - location: "~"
    mountPoint: null
    writable: null
    sshfs:
      cache: null
      followSymlinks: null
      sftpDriver: null
  - location: "/tmp/lima"
    writable: true

#Default - virtio-fs, alternatively we can support reverse-sshfs as well.
mountType: "virtio-fs"

video:
  #Only display vz will be support for driver type vz
  display: vz
networks:
#Need to think more on this on how to provide host to guest communication, vz support NAT and Bridge networks models
#We should implement slirp network for the guest to host communication
```
With this above configurations, We must need to do some driver specific yaml validations as well. 

This will be the first steps. Based on the integration model we choose I can come up with a set of checklists on what needs to be done.
