### DISCUSSION TITLE
invalid network_mode: host when run `nerdctl compose up `

### DISCUSSION THREAD

**Discussion by saltbo** [lima-vm/lima#964] [Q&A] [answered]
### Description

```yaml
version: "3"

services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    # command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug", "--component-log-level", "upstream:debug"]
    container_name: envoy
    network_mode: host
    volumes:
      - "./configs:/etc/envoy"
    # ports:
    #   - "9901:9901"
    #   - "8000:8000"
    #   - "8081:8081"
    #   - "8082:8082"

```
with ports
![image](https://user-images.githubusercontent.com/17308208/179186806-1dbb99de-1d48-4df7-9798-aa58ca36e5a0.png)

with network_mode
![image](https://user-images.githubusercontent.com/17308208/179186619-fcbe08d2-b17e-412a-b1b4-93fbb7cf60b4.png)
