### DISCUSSION TITLE
Beginner question: possible to run xterm (without installing XQuartz)?

### DISCUSSION THREAD

**Discussion by emendelson** [lima-vm/lima#987] [Q&A]
Am I right to think that it's impossible to run xterm under lima? I haven't tried installing XQuartz, but am ready to do so if it's needed for xterm).

I'm able to install xterm but when I try to run it, I get:

```
xterm: Xt error: Can't open display: 
xterm: DISPLAY is not set
```

I haven't found any working solutions, but maybe I'm looking in the wrong place.

**Comment by afbjorklund** [comment]
You can configure some kind of graphical output for the VM, start an Xorg server and then even connect to it with a container.

Here is how it was done with Docker and VirtualBox, for instance: https://github.com/boot2docker/boot2docker/pull/1289 (for `docker-machine`)

To start the display, there is a matching entry in the yaml:

```yaml
video:
  # QEMU display, e.g., "none", "cocoa", "sdl", "gtk".
  # As of QEMU v6.2, enabling this is known to have negative impact
  # on performance on macOS hosts: https://gitlab.com/qemu-project/qemu/-/issues/334
  # 🟢 Builtin default: "none"
  display: null

```

We should prepare an "xterm" (or xeyes) example for lima.

**Reply by afbjorklund** [reply]
When starting up in CLI mode, the qemu display should look something like:

![lima-default-gtk](https://user-images.githubusercontent.com/10364051/180638516-5e846248-bb4c-4672-9b72-8ffabdd3d27e.png)

After adding "x11-apps" (and dependencies, for instance `xorg` and `openbox`)

![lima-default-x11](https://user-images.githubusercontent.com/10364051/180638544-d564a696-711a-401d-8c4f-df5e16aae266.png)

I added a local user called "lima" with a password, so I could log in and `startx`.

That also means I have to run `containerd-rootless-setuptool.sh install` again.

----

This was just an example, normally you would configure `openbox-session`:

[Using Openbox without a desktop environment (The lightweight approach)](http://openbox.org/wiki/Help:Getting_started#Using_Openbox_without_a_desktop_environment_.28The_lightweight_approach.29)

More information about running GUI applications inside Linux containers:

https://github.com/mviereck/x11docker

**Reply by afbjorklund** [reply]
It would probably be a lot more straightforward, to use `limactl show-ssh` and Xquartz.

Still requires some setup like X11Forwarding and such, so probably requires documentation.

```yaml
ssh:
  # Forward X11 into the instance
  # 🟢 Builtin default: false
  forwardX11: null
  # Trust forwarded X11 clients
  # 🟢 Builtin default: false
  forwardX11Trusted: null

```

EDIT: Added a feature request to the backlog, to provide more docs for running GUI apps:

* https://github.com/lima-vm/lima/issues/989

**Comment by afbjorklund** [comment]
There is also a backlog item about adding Wayland support:

* https://github.com/lima-vm/lima/issues/2

**Comment by emendelson** [comment]
Thank you for these. My goal is set up a system for myself (and provide instructions for others) for running WordPerfect for Unix (character-mode version) in xterm, making it possible to use the graphic equation editor, etc. The WordPerfect for Unix project is here: 

https://github.com/taviso/wpunix

And I want to provide instructions at my WordPerfect site, http://wpdos.org

This project works well in lima, running in the macOS terminal, but it would be good to make it easy to setup with a graphic terminal. If it's possible to provide an example for running xterm, I'll be grateful. I'm not clear on exactly what steps to take right now. Thank you again for looking into this!

**Reply by afbjorklund** [reply]
This can probably run in a regular terminal window even with the ssh connection, but anyway....

From the original `limactl start`, or afterwards using `limactl edit`, you need to enable the display.

Choosing "default" instead of "none", should do it: (you can also select a specific backend, like "cocoa")

```yaml
video:
  display: "default"
```

---

Then after the machine has been started, you login with the default shell and install the packages.

```console
anders@lima-default:/home/anders$ sudo apt install xterm xorg openbox fbpanel
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ...
Suggested packages:
  ...
The following NEW packages will be installed:
  ...
0 upgraded, 179 newly installed, 0 to remove and 78 not upgraded.
Need to get 86.6 MB of archives.
After this operation, 324 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

It is possible to slim the install down (or make it bigger). After that I also added a second local user:

```console
anders@lima-default:/home/anders$ sudo adduser lima
Adding user `lima' ...
Adding new group `lima' (1001) ...
Adding new user `lima' (1001) with group `lima' ...
Creating home directory `/home/lima' ...
Copying files from `/etc/skel' ...
New password: 
Retype new password: 
passwd: password updated successfully
Changing the user information for lima
Enter the new value, or press ENTER for the default
	Full Name []: 
	Room Number []: 
	Work Phone []: 
	Home Phone []: 
	Other []: 
Is the information correct? [Y/n] 
```

After that you should be able to login as "lima", and run `startx` to start X11 (`xterm` on right click menu).

**Reply by afbjorklund** [reply]
There were some links above, how to configure the minimal window manager (requires some setup).

I had to enable a software cursor (in xorg.conf) and added some startup programs (like e.g. [fbpanel](https://aanatoly.github.io/fbpanel/)).

You can also set the screen size using `xrandr -s 1024x768`, and `hsetroot` to set the background.

![lima-default-gui](https://user-images.githubusercontent.com/10364051/180649598-c86af829-e023-4c24-a891-6f6cb4fb7a05.png)

See http://openbox.org/wiki/Help:Autostart, there is lots of information available on how to set up X11...

**Comment by emendelson** [comment]
Making progress, but baffled by some things still.

*Before* adding `"default"` to the displays line, I logged in with my own name and did:

`sudo apt install xterm xorg openbox fbpanel`

and also

`sudo adduser lima` (as described above).

I then added `"default"` to the displays line in lima.yaml, and started the default system.

QEMU started up, and I was able to log in as `lima` but not as my own user name, which was rejected. Is there any way I can log in with my own username?

Also, I tried starting xterm, but that gives me this error:
```
xterm: Xt error: can't open display:
xterm: DISPLAY is not set
```
So I have two questions: 

1. How can I log in to the QEMU interface with my own username?
2. How can I start xterm in the QEMU interface?
3. And I realize that this all may be pointless, since I can't seem to get access to host file system from the QEMU system, and that makes the word-processor basically useless.

**Reply by afbjorklund** [reply]
You **can** log in with your own user, by setting a password (using `passwd`) for it. By default, it only has ssh keys (no password).

You need to start the X server, before you can start any X clients such as xterm. This is normally done using `startx` command.

![lima-login-startx](https://user-images.githubusercontent.com/10364051/180656002-ca168a3c-5bfd-4c05-a693-103c70bf8e6a.png)

With the spartan install above, it will just show a black window (until configured) - but it does have a context menu (right-click).

![lima-context-menu](https://user-images.githubusercontent.com/10364051/180656191-85d970b2-bdf4-44c6-b813-cf993fcd767c.png)

You should be able to access the file mounts as usual, by default lima will mount your home directory (R/O) and /tmp/lima (R/W)

```yaml
# 🟢 Builtin default: null (Mount nothing)
# 🔵 This file: Mount the home as read-only, /tmp/lima as writable
mounts:
- location: "~"
  # Configure the mountPoint inside the guest.
  # 🟢 Builtin default: value of location
  mountPoint: null
  # CAUTION: `writable` SHOULD be false for the home directory.
  # Setting `writable` to true is possible, but untested and dangerous.
  # 🟢 Builtin default: false
  writable: null
- location: "/tmp/lima"
  # 🟢 Builtin default: false
  # 🔵 This file: true (only for "/tmp/lima")
  writable: true
```
