### DISCUSSION TITLE
Provision scripts can't find mounted host files.

### DISCUSSION THREAD

**Discussion by Regrau** [lima-vm/lima#994] [Q&A] [answered]
Hi, are the provision scripts that are declared in the config run before or after the Filesystem is mounted?

```
# This example requires Lima v0.7.0 or later
images:
- location: https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64.qcow2
  arch: "aarch64"
cpus: 4
memory: "8GiB"
mounts:
  - location: "~/Documents/dev-runtime"
    mountPoint: "/usr/local/share/dev-runtime"
    writable: true
provision:
- mode: system
  script: |
    #!/bin/bash
    zypper -n in sshfs kitty
    echo "user_allow_other" > /etc/fuse3.conf
- mode: user
  script: |
    #!/bin/bash
    cd /usr/local/share/dev-runtime 
    ./bootstrap.sh playbook.yml
```

This fails with the error 
```
[   52.000542] cloud-init[1053]: /home/regrau.linux/.lima-user-script: line 9: ./bootstrap.sh: No such file or directory
[   52.001237] cloud-init[1053]: LIMA| WARNING: Failed to execute /mnt/lima-cidata/provision.user/00000001 (as user regrau)
```

And I can't understand why or how to fix it. The dev runtime is an ansible playbook which provisions the machine. The `bootstrap.sh` file is an installation script for ansible.
