### ISSUE TITLE
add opensuse-tumbleweed for aarch64

### ISSUE THREAD

**Issue by replicajune** [lima-vm/lima#1011]
### Description

Hello,

After some digging and copy pasting stuff around, I was able to make tumbleweed working on aarch64 using the following yaml config file:

``` yaml
images:
- location: http://download.opensuse.org/ports/aarch64/tumbleweed/appliances/openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64.qcow2
  arch: "aarch64"
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
provision:
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail
    zypper refresh
    zypper install -y sshfs
    for FILE in fuse fuse3; do echo 'user_allow_other' >> "/etc/${FILE}.conf"; done
```

is it something I can propose a merge request in `/examples/experimental/opensuse-tumbleweed.yaml` ?

I would:
- add the new aarch64 location
- setup the script to have the requirement for mount point in place
- keep the comments in place from the original file

However as I don't own a x64 mac machine I wouldn't be able to make sure that the script properly runs on `x86_64`. Maybe someone could review it and test it ? :)
