### ISSUE TITLE
Rootful CNI port forwarder does not work for CentOS 7

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1038]
Rootful CNI port forwarder does not work for CentOS 7, although it works for other templates

YAML:
```yaml
images:
- location: "https://cloud.centos.org/altarch/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2"
  arch: "x86_64"
  digest: "sha256:e38bab0475cc6d004d2e17015969c659e5a308111851b0e2715e84646035bdd3"
containerd:
  system: true
  user: false
firmware:
  legacyBIOS: true
cpuType:
  x86_64: "Haswell-v4"
```

`lima sudo /usr/local/bin/nerdctl run -it --rm -p 8080:80 nginx:alpine` does not seem to expose the port 8080.

Tested v0.10.0, v0.11.3, and master 1af48114f55b0c80eaf0981f6ffcf7a7550f3f7c
