### ISSUE TITLE
YAML: duplicated keys should raise an error (with human-readable message)

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1044]
The following YAML is invalid but currently silently treated as a bridge-only YAML: https://github.com/lima-vm/lima/pull/851#issuecomment-1238877987

```yaml
networks:
- lima: shared
  lima: bridged
# ↑ typo of `- lima: bridged`
```
