### ISSUE TITLE
can not get the logs forr the k3s when set http_proxy

### ISSUE THREAD

**Issue by saltbo** [lima-vm/lima#1113]

**Comment by jandubois** [comment]
> Why override the env define from lima.yaml? I think it's should have high-level priority

It was intentional that the process environment would override the `lima.yaml` settings. Maybe that was a mistake, but it would be a breaking change to modify that now.

I need to think about this a bit more, but maybe appending `192.168.5.2,192.168.5.15,127.0.0.1,localhost` to whatever value the user specifies for `noproxy` would be the right thing, as these should **never** be proxied, regardless of what else the user wants to exclude.

**Comment by saltbo** [comment]
before resolving it, my solution such as:

```yaml
provision:
- mode: system
  script: |
    #!/bin/sh
    # curl -sfL https://get.k3s.io | sh -
    export no_proxy="192.168.5.2,192.168.5.15,127.0.0.1,localhost"
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.15+k3s1 sh -
```
