### ISSUE TITLE
[9p] chown: changing ownership of 'xxx': Operation not permitted

### ISSUE THREAD

**Issue by nulllpoint** [lima-vm/lima#1169]
### Description

I read the issuse #231 , has it been solved now?

I use podman by lima-vm, container is mysql/mysql-server, it need `chown mysql:mysql xxx`, but when use -v mapping host's dir , propmpt `chown: changing ownership of 'xxx': Operation not permitted`
macos version: 12.6 
lima version: 0.13.0
qemu version: 7.1.0
lima's yaml config: 
```yaml
mountType: 9p
mounts:
- location: "/Users/xxx/lima_workspace/podman"
  writable: true
  9p:
    cache: mmap
```
mysql docker hub:
```yaml
docker hub : https://hub.docker.com/r/mysql/mysql-server
fetch cmd: docker pull mysql/mysql-server:8.0.21
```

I also try to use chown directly in lima-vm, neither.
```shell
[xxx@lima-test test]$ sudo groupadd test
[xxx@lima-test test]$ sudo useradd -g test test
[xxx@lima-test test]$ ll
drwxr-xr-x. 4 xxx games 128 Nov 16 08:55 mysql
drwxrwxr-x. 2 xxx games  64 Nov 16 08:48 test
[xxx@lima-test test]$ chown test:test test
chown: changing ownership of 'test': Operation not permitted
```

**Comment by AkihiroSuda** [comment]
https://github.com/lima-vm/lima/blob/c3e82cc884eb6f4280c86f0ee4a25ee1756ff987/examples/default.yaml#L74-L78

`securityModel: "mapped-xattr"` enables chown, but incompatible with symlinks

**Comment by nulllpoint** [comment]
> https://github.com/lima-vm/lima/blob/c3e82cc884eb6f4280c86f0ee4a25ee1756ff987/examples/default.yaml#L74-L78
> 
> `securityModel: "mapped-xattr"` enables chown, but incompatible with symlinks

Thank you for your reply, but it still seems to be unresolved.
That is my `lima.conf`,  pass the `limactl validate`
```yaml
mountType: 9p
mounts:
- location: "/Users/xxx/lima_workspace/test"
  writable: true
  9p:
    cache: "mmap"
    securityModel: "mapped-xattr"
- location: "/tmp/lima"
  writable: true
```

and i deleted the old folder and recreated ,  it's still...
```shell
[xxx@lima-test test]$ pwd
/Users/xxx/lima_workspace/test
[xxx@lima-test test]$ chown test:test test
chown: changing ownership of 'test': Operation not permitted
```
