### ISSUE TITLE
Flatcar Container Linux support

### ISSUE THREAD

**Issue by kullervo610** [lima-vm/lima#1372]
### Description

Flatcar Container Linux [(https://www.flatcar.org/)](https://www.flatcar.org/) is an interesting immutable Linux OS which suits well to run e.g. Kubernetes. Any change support for Flatcar Linux can be added to Lima as it does not seem to work "out-of-the-box" based on quick testing done.

**Comment by afbjorklund** [comment]
I think that Flatcar (and CoreOS) use ignition rather than cloud-init, so I'm not sure it is compatible.

**Comment by afbjorklund** [comment]
Note that you can run Podman Desktop instead of Rancher Desktop, if you want Fedora CoreOS support...

It is "interesting immutable", and has a common ancestor with Container Linux (that would be: CoreOS)

**Comment by afbjorklund** [comment]
Are you able to provide a YAML file, for the "stable" image ?

**Comment by afbjorklund** [comment]
Currently there is no support for compressed images in Lima, so the .bz2 needs to be decompressed.

**Comment by afbjorklund** [comment]
```yaml
images:
#- location: "https://stable.release.flatcar-linux.net/amd64-usr/3374.2.5/flatcar_production_qemu_image.img.bz2"
#  arch: "x86_64"
#  digest: "sha256:cb8a30d891f1a9c4dd3fe34508c2f00aa2f18956bbe48f649848201292ffd1a9"
- location: "flatcar_production_qemu_image.img"
  arch: "x86_64"
  digest: "sha256:28f570a120f040523972a7cae948eb6ee41cf444f3c7c92f1bc721bf95ee5891"

video:
  display: "default" 
```

For some reason, Flatcar produces every checksum - except for SHA256...


```
# MD5 HASH
0a8b08387670cbc62c2d5086622a0956  flatcar_production_qemu_image.img.bz2
# SHA1 HASH
52edb61aacf14e19f23716d20311197fe47a9fa9  flatcar_production_qemu_image.img.bz2
# SHA512 HASH
7aa371a6e7013d02f6e3d6031c155420ce617dfe920d4d744950f87faa6b6f83c5e938525fcba5e8d1fb885e647af20fb412c3b56dbaff1a2d3dfcf7815a3145  flatcar_production_qemu_image.img.bz2
```

**Comment by afbjorklund** [comment]
The issue was not the OEM, it was that the labels and paths for `user-cloudinit` are hardcoded...

* The label of the CD is "config-2", not "cidata"

* The mount path of it is "/media/configdrive", not "/mnt/lima-cidata"

* The name of the file is "openstack/latest/user_data", not "user-data"

**Comment by AkihiroSuda** [comment]
@afbjorklund Thanks for taking a look, it looks like these files need to be modified?
https://github.com/flatcar/coreos-cloudinit/search?q=%2Fmedia%2Fconfigdrive

**Comment by afbjorklund** [comment]
Maybe they (the locations) can be configured during runtime somehow, env or cmdline ?

**Comment by afbjorklund** [comment]
Apparently there is a special image for UEFI, noticed when looking at the arm64 variant.

Debug setup:
```yaml
images:
- location: "https://stable.release.flatcar-linux.net/amd64-usr/3374.2.5/flatcar_production_qemu_uefi_image.img.bz2"
  arch: "x86_64"
  digest: "sha512:3fe0068f838f8055fbdc374e9d59ab6828d79f1d1d3c0b93fe6b89893ff06d1cbc4acdd19c0c6a54e7462cf86cdd29340eaa2ed6ad3fd114c552f43bce526718"
- location: "https://stable.release.flatcar-linux.net/arm64-usr/3374.2.5/flatcar_production_qemu_uefi_image.img.bz2"
  arch: "aarch64"
  digest: "sha512:0f4ee08e9a17ece104d477cbc1ab0eda6f410683aea0067779771587c3864df9f3527c1c647158064424b33918fd5bbabf6384e9d71ef4a98a672565d154aba8"

video:
  display: "default"

```
