### ISSUE TITLE
Add support for SUSE's MicroOS

### ISSUE THREAD

**Issue by e-minguez** [lima-vm/lima#1456]
### Description

https://en.opensuse.org/Portal:MicroOS

**Comment by e-minguez** [comment]
I'm currently trying to make it work but unfortunately it seems the `/mnt` mountpoint is read only so the `mkdir -p -m 700 "${LIMA_CIDATA_MNT}"` command here https://github.com/lima-vm/lima/blob/master/pkg/cidata/cidata.TEMPLATE.d/user-data#L35 fails.

However I'm able to ssh into the VM properly. It seems the `LIMA_CIDATA_MNT` variable is _hardcoded_ https://github.com/lima-vm/lima/blob/master/docs/internal.md#environment-variables-1 I guess it would be nice to make it configurable (?)

The configuration file I've used is this one:

```
# This example requires Lima v0.7.0 or later
images:
# Hint: run `limactl prune` to invalidate the "Current" cache
- location: https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2
  arch: "x86_64"
- location: https://download.opensuse.org/ports/aarch64/tumbleweed/appliances/openSUSE-MicroOS.aarch64-OpenStack-Cloud.qcow2
  arch: "aarch64"
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
```

I think this is related to #1372 as well.
