### ISSUE TITLE
Ability to set the VM hostname during the provisioning

### ISSUE THREAD

**Issue by jay7x** [lima-vm/lima#1467]
### Description

As I see the VM hostname is hardcoded to `lima-<vm_name>` in the `cidata.TEMPLATE.d/meta-data`. That causes some inconvenience in a complex scenarios when multiple VMs are clustered because internal hostname doesn't match the name used to refer a VM from outside.

I can work this around by calling the `hostnamectl set-hostname {{.Name}}` in a provisioning script but this might cause some issues with services started before.. so ideally reboot is required to be on a safe side.

So it'd be much nicer to either a) set the hostname to the VM name by default or b) to be able to configure the hostname in the VM YAML definition or c) to be able to set it via cmdline flag of `limactl start` command.

**Comment by jay7x** [comment]
It seems the provisioning scripts are not expanded with the templating engine:

```yaml
  provision:
    - mode: system
      script: |
        #!/bin/bash
        hostnamectl set-hostname '{{.Name}}'
```

leads to

```
$ hostname
Name
```

**Comment by jay7x** [comment]
worked that around with
```bash
HOSTNAME=$(hostname)
hostnamectl set-hostname "${HOSTNAME#"lima-"}"
```

**Comment by jandubois** [comment]
> It seems the provisioning scripts are not expanded with the templating engine:
> 
> ```yaml
>   provision:
>     - mode: system
>       script: |
>         #!/bin/bash
>         hostnamectl set-hostname '{{.Name}}'
> ```

No, but you can use the `$LIMA_CIDATA_NAME` environment variable:

```yaml
provision:
- mode: system
  script: |
    hostname $LIMA_CIDATA_NAME
```
