### ISSUE TITLE
Invalid YAML syntax not caught by validate and silently failing

### ISSUE THREAD

**Issue by kalikiana** [lima-vm/lima#1503]
### Description

So this was confusing me a fair bit almost thinking there was a race condition with the provisioning or maybe the image I was using. Suffice it to say it's neither. Consider the following snippet which prepares an instance with [distrobox](https://github.com/89luca89/distrobox) and a default container:

```
images:
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"

provision:
- mode: system
  script: |
    #!/bin/sh
    command -v distrobox >/dev/null 2>&1 && exit 0
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends podman flatpak
- mode: system
    #!/bin/sh
    curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh
- mode: user
  script: |
    #!/bin/sh
    distrobox create --yes
probes:
- script: |
    #!/bin/bash
    set -eux -o pipefail
    timeout 30s bash -c "until command -v podman >/dev/null 2>&1; do sleep 3; done"
  description: podman to be installed
- script: |
    #!/bin/bash
    set -eux -o pipefail
    timeout 30s bash -c "until command -v distrobox >/dev/null 2>&1; do sleep 3; done"
  description: distrobox to be installed
```

Apparently the missing `script:` key is never caught, and it leads to the instance booting fine but with only `podman` installed.

`limactl validate` doesn't seem to detect this either.

**Comment by afbjorklund** [comment]
It's actually worse, the next step is silently discarded too.

```yaml
provision:
- mode: system
  script: |
    #!/bin/sh
    command -v distrobox >/dev/null 2>&1 && exit 0
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends podman flatpak
- mode: system
    #!/bin/sh
    curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh
- mode: user
  script: |
    #!/bin/sh
    distrobox create --yes
```

```yaml
provision:
- mode: system
  script: "#!/bin/sh\ncommand -v distrobox >/dev/null 2>&1 && exit 0\nDEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends podman flatpak\n"
- mode: system
  script: ""
```


The standalone tools are finding it, but not goccy go-yaml ?

```console
$ yamllint examples/distrobox.yaml 
examples/distrobox.yaml
  14:6      warning  missing starting space in comment  (comments)
  15:5      error    syntax error: expected <block end>, but found '<scalar>' (syntax)

$ yq examples/distrobox.yaml
Error: bad file 'examples/distrobox.yaml': yaml: line 12: did not find expected key
```
