### ISSUE TITLE
[Feature Request] Support ArchLinux ARM

### ISSUE THREAD

**Issue by sainnhe** [lima-vm/lima#155]
https://github.com/lima-vm/lima/blob/82e1465300f5399cd6a26122e2dae7c8f266e489/examples/archlinux.yaml#L1-L20

Looks like the current image is x86_64 architecture, but there is another project aiming to port archlinux to arm: [ArchLinux Arm](https://archlinuxarm.org/).

IMO the performance should be better on m1 mac.

**Comment by AkihiroSuda** [comment]
If there is a qemu image with cloud-init, it should already work

**Comment by mcginty** [comment]
FYI, I've started working on this by modifying the `arch-boxes` project (the code that builds the x86_64 "cloudimg" image) and the only step left is to get cloud-init installed.

https://github.com/mcginty/arch-boxes

Right now it uses Clear Linux's [`ucd`](https://github.com/clearlinux/micro-config-drive) which only handles the OpenStack cloud-init format, and Lima uses `nocloud` so we'll need to get the full-fledged cloud-init working (`cloud-init` isn't on Arch Linux ARM's official repository, unlike the vanilla Arch repos).

**Comment by sainnhe** [comment]
The architecture of `cloud-init` is `any` so maybe we can directly build this package on arch linux arm.

```shell
$ sudo pacman -S asp
$ asp checkout cloud-init
$ cd cloud-init/trunk
$ makepkg -si
```

**Comment by mcginty** [comment]
@sainnhe it doesn't build as-is, but with some modification it works. I'm working on hacking it together, then can make contributions upstream.

I got cloud-init building, though, and am almost to a working cloudimg build :).

**Comment by mcginty** [comment]
Got a build working! I haven't done any extensive testing, but limactl successfully downloads and starts the VM for me, and cloud-init seems to be working as expected.

Here's an example YAML (i.e. `archlinuxarm.yaml`):

```yaml
# This example requires Lima v0.7.0 or later
images:
# NOTE: the image is periodically rotated, if you face 404, see https://mirror.pkgbuild.com/images/ to find the latest image.
- location: "https://github.com/mcginty/arch-boxes/releases/download/v20220322/Arch-Linux-aarch64-cloudimg-20220322.0.qcow2"
  arch: "aarch64"
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
```
