### ISSUE TITLE
command not found even if I installed it

### ISSUE THREAD

**Issue by developer-guy** [lima-vm/lima#1583]
### Description

Here is my template to launch lima vm, as you can see that I'm trying to install wolfictl tool into it, but the VM that I launched didn't have that binary, did I do something wrong?

```yaml
images:
- location: "https://github.com/lima-vm/alpine-lima/releases/download/v0.2.27/alpine-lima-std-3.17.0-x86_64.iso"
  arch: "x86_64"
  digest: "sha512:07b88838734de63edf302a531aaf57f5a48ec31b31b8a95740faa4fac11852b375c5c83180ff34311ee284b8123536b86b70f0606591b1986e9af2268f3ea675"
- location: "https://github.com/lima-vm/alpine-lima/releases/download/v0.2.27/alpine-lima-std-3.17.0-aarch64.iso"
  arch: "aarch64"
  digest: "sha512:b8028c96385ea5be499e37c142cb9e9d9c861f2647ff7f8cceaf867961ef8878e34a8ba0e8cfe2e01ac082191048e7acc30534782b13c5ec4bea53dad5919c33"
cpus: 2
memory: 8GiB
disk: 20GiB
firmware:
  legacyBIOS: true
containerd:
  system: false
  user: false
mounts:
- location: "~"
  writable: true
- location: "/tmp/lima"
  writable: true
provision:
- mode: system
  script: |
    #!/bin/sh
    set -eux -o pipefail
    apk update
    apk add --update --no-cache vim git make bubblewrap curl tar go
    git clone https://github.com/wolfi-dev/wolfictl.git
    (cd wolfictl && make install)
message: |-
  ---
  Run the following to get a root shell
    limactl shell test-playground sudo su -c "HOME=\"${HOME}\" ash"
  ---
```
