### ISSUE TITLE
Provide the size of the disk image, along with the checksum and url

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#1586]
### Description

I know that one can ask the server, but maybe it is down or slow.

When we automate the checksumming ("digest"), we could have it populate the byte size as well ?

```yaml
images:
# Try to use release-yyyyMMdd image if available. Note that release-yyyyMMdd will be removed after several months.
- location: "https://cloud-images.ubuntu.com/releases/22.10/release-20230413/ubuntu-22.10-server-cloudimg-amd64.img"
  arch: "x86_64"
  size: 762445824
  digest: "sha256:d46438111d7a6dfcdfb2e1fb76762a79d56f09dc308cc9ab2300effc0078fd5b"
- location: "https://cloud-images.ubuntu.com/releases/22.10/release-20230413/ubuntu-22.10-server-cloudimg-arm64.img"
  arch: "aarch64"
  size: 739573760
  digest: "sha256:e1865c2ebc531600ae6012d86fa2dae5846e7801cdcdbcf90d9c830218ef4ae9"
# Fallback to the latest release image.
# Hint: run `limactl prune` to invalidate the cache
- location: "https://cloud-images.ubuntu.com/releases/22.10/release/ubuntu-22.10-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/22.10/release/ubuntu-22.10-server-cloudimg-arm64.img"
  arch: "aarch64"
```

A disk size of "0" would just mean that we don't know, before contacting (or that the image is generic)
