### ISSUE TITLE
M1 Mac running an x86 Lima instance consistently freezes on Ventura 13.4.1 on a brew installed lima.

### ISSUE THREAD

**Issue by nemonik** [lima-vm/lima#1649]
### Description

On an M1 Pro with the following instance config (note the arch is `x86_64`) running on Ventura 13.4.1 on a brew installed lima.  my Ubuntu Jammy Lima VM starts, but freezes doing the following

```
sudo apt-get update
sudo apt-get upgrade
```

The instance freeze mid upgrade and later after `limactl stop...` in a `sudo dpkg --configure -a`.

I've tried tweaking CPU and memory settings and the same thing happens.  

The problem consistently happens.

Prior to upgrading to Ventura my `x86_64` instances worked fine.  I'm not sure what other changes occurred prior to upgrading.  Maybe I should build and install lima from source?

Here is my config file with comments stripped for brevity:

```
arch: x86_64

images:
# Try to use release-yyyyMMdd image if available. Note that release-yyyyMMdd will be removed after several months.
- location: "https://cloud-images.ubuntu.com/releases/22.04/release-20220712/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
  digest: "sha256:86481acb9dbd62e3e93b49eb19a40c66c8aa07f07eff10af20ddf355a317e29f"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release-20220712/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"
  digest: "sha256:e1ce033239f0038dca5ef09e582762ba0d0dfdedc1d329bc51bb0e9f5057af9d"
# Fallback to the latest release image.
# Hint: run `limactl prune` to invalidate the cache
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"

cpus: null

memory: null

disk: null

mounts:
- location: "~"
  mountPoint: null
  writable: true
  sshfs:
    cache: null
    followSymlinks: null
    sftpDriver: null
  9p:
    securityModel: null
    protocolVersion: null
    msize: null
    cache: null
- location: "/tmp/lima"
  writable: true

mountType: null

ssh:
  localPort: 0
  loadDotSSHPubKeys: null
  forwardAgent: null
  forwardX11: null
  forwardX11Trusted: null

caCerts:
  removeDefaults: null

containerd:
  system: null
  user: null

cpuType:
  aarch64: null
  x86_64: null

firmware:
  legacyBIOS: null

video:
  display: null

propagateProxyEnv: null

hostResolver:
  enabled: false
  ipv6: null
  hosts:

dns:
 - 100.64.0.1
```

The instance spin up but freezes on 

```
update-initramfs: Generating /boot/initrd.img-6.2.0-20-generic
```

I cannot open another shell on the instance nor can interrupt the process.  If open another shell watching processes prior to the `sudo apt-get upgrade` the shell will lock too.

When I go to stop the instance it doesn't stop smoothly

```
INFO[0000] Sending SIGINT to hostagent process 61430
INFO[0000] Waiting for the host agent and the driver processes to shut down
INFO[0000] [hostagent] Received SIGINT, shutting down the host agent
INFO[0000] [hostagent] Shutting down the host agent
INFO[0000] [hostagent] Stopping forwarding "/run/lima-guestagent.sock" (guest) to "/Users/mjwalsh/.lima/mep-amd64/ga.sock" (host)
INFO[0000] [hostagent] Unmounting "/Users/mjwalsh"
INFO[0000] [hostagent] Unmounting "/tmp/lima"
INFO[0000] [hostagent] Shutting down QEMU with ACPI
INFO[0000] [hostagent] Sending QMP system_powerdown command
FATA[0180] did not receive an event with the "exiting" status
```

I tried uninstalling brew installed qemu 8.0.2 and installing my own tap of 8.0.0, but the same thing happens.

I'm lost as what to do.

Is there something I can do to provide insight and are others seeing this?
