### ISSUE TITLE
Reverse unix socket forwarding in Mac deletes the source unix socket.

### ISSUE THREAD

**Issue by RangelReale** [lima-vm/lima#1724]
### Description

limactl version 0.16.0

I'm trying to run Docker Desktop on my M2 Mac, and connecting to its unix socket from inside the lima vm. So I created this configuration:

```
portForwards:
- guestSocket: "/run/user/{{.UID}}/docker.sock"
  hostSocket: "/Users/rangelreale/.docker/run/docker.sock"
  reverse: true
```

it seems to work, but the unix socket stops work both in the host and in the guest
host:
```
$ docker container ls
Cannot connect to the Docker daemon at unix:///Users/rangelreale/.docker/run/docker.sock. Is the docker daemon running?
```

guest:
```
docker container ls
error during connect: Get "http://%2Frun%2Fuser%2F501%2Fdocker.sock/v1.24/containers/json": read unix @->/run/user/501/docker.sock: read: connection reset by peer
```

It seems that when using `reverse: true`, the host socket is being deleted, according to @afbjorklund in slack.
