### ISSUE TITLE
Remove conf file again, when the instance shuts down

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#1737]
### Description

Currently when we forward a socket, it is created when the instance is started and removed when the instance is stopped.

e.g. docker, podman

But when we copy client configuration, it is created when the instance is started - but _never_ removed, even if it is invalid...

e.g. k8s, k3s

It would be good to have an optional flag, to remove the file again when the instance is stopped:

```yaml
# Copy files from the guest to the host. Copied after provisioning scripts have been completed.
# copyToHost:
# - guest: "/etc/myconfig.cfg"
#   host: "{{.Dir}}/copied-from-guest/myconfig"
# # "guest" can include these template variables: {{.Home}}, {{.UID}}, and {{.User}}.
# # "host" can include {{.Home}}, {{.Dir}}, {{.Name}}, {{.UID}}, and {{.User}}.
# # default: delete: false
copyToHost:
- guest: "/etc/kubernetes/admin.conf"
  host: "{{.Dir}}/copied-from-guest/kubeconfig.yaml"
  delete: true
```

So when `delete: true` is set, the local file will be deleted again when the instance is stopped.

This will avoid trying to contact the local cluster, only to be met with a connection error or timeout.

----

* https://github.com/lima-vm/lima/issues/1300
