### ISSUE TITLE
Integrated VDE networking support

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#175]
I think Lima should manage the VDE networking setup for the user. I would like to make it work like this:

## Lima Network Configuration

Managed networks are declared in `$LIMA_HOME/_config/networks.yaml`. Lima will provide a default configuration:

```yaml
# Paths to vde executables. Because vde_vmnet is invoked via sudo it should be
# installed where only root can modify/replace it. This means also none of the
# parent directories should be writable by the user.
#
# The var_run directory also must not be writable by the user because it will
# include the vde_vmnet pid files. Those will be terminated via sudo, so replacing
# the pid files would allow killing of arbitrary privileged processes.
paths:
  vde_switch: /opt/vde/bin/vde_switch
  vde_vmnet: /opt/vde/bin/vde_vmnet
  var_run: /var/run/lima

group: staff

networks:
  shared:
    mode: shared
    gateway: 192.168.105.1
    dhcp-end: 129.168.105.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: en0
    # bridged mode doesn't has a gateway; dhcp is managed by outside network
  host:
    mode: host
    gateway: 192.168.106.1
    dhcp-end: 129.168.106.254
    netmask: 255.255.255.0
```

Users can modify existing networks (e.g. change the dhcp range), or define additional ones.

## Instance Network Configuration

The managed networks can be referenced from an instance's `lima.yaml` using a custom `lima://` VNL scheme:

```
networks:
  vde:
  - vnl: lima://shared
    name: nat
  - vnl: lima://host
```

The default name for networks with a `lima://` VNL will be the network name, not `vdeN`. So the config above will create a `nat` and a `host` interface inside the instance.

Whenever Lima starts an instance, it will check if all referenced networks are already running, and if not, start both `vde_switch` and `vde_vmnet` daemons for that network. Sockets and pid files will be stored under `/var/run/lima`. Log files will be stored under `$LIMA_HOME/_vde`. (Or should we put them into `/var/run/lima` as well? Maybe needs another setting under `paths`.)

When an instance is stopped, Lima will check if there are networks that are no longer being used, and shut them down as well.

## Managing root privileges

`vde_vmnet` has to be run as root, so Lima will start and stop it using `sudo`. This will ask the user for their admin password unless they have enabled password-less `sudo`.

A helper command for more locked-down systems will be implemented to allow Lima to manage networks without asking for the password every time a network is started or stopped:

```console
$ limactl sudoers | sudo tee /etc/sudoers.d/lima
```

This will write the specific commands needed to start and stop the daemons to `/etc/sudoers.d/lima`, e.g.

```
Cmnd_Alias SHARED_SWITCH_START = /opt/vde/bin/vde_switch --sock=/var/run/lima/shared.ctl \
                                 --pidfile=/var/run/lima/shared_switch.pid --group=staff --dirmode=0770
Cmnd_Alias SHARED_SWITCH_STOP  = /usr/bin/pkill -F /var/run/lima/shared_switch.pid

Cmnd_Alias SHARED_VMNET_START  = /opt/vde/bin/vde_vmnet --vmnet-mode=shared /var/run/lima/shared.ctl
Cmnd_Alias SHARED_VMNET_STOP   = /usr/bin/pkill -F /var/run/lima/shared_vmnet.pid

%staff ALL=(root:root)    NOPASSWD:NOSETENV: /bin/mkdir -m 755 -p /var/run/lima
%staff ALL=(daemon:staff) NOPASSWD:NOSETENV: SHARED_SWITCH_START, SHARED_SWITCH_STOP
%staff ALL=(root:root)    NOPASSWD:NOSETENV: SHARED_VMNET_START,  SHARED_VMNET_STOP
```

(Real settings will include `gateway`, `dhcp-end`, `netmask`, etc too. Also `vde_vmnet` doesn't yet support writing a pid file.)

Question: do we really need to run `vde_switch` using the `daemon` user? We run all of `qemu` under the actual user account; is there anything in the switch that makes it more risky than other utilities, so it needs to be segregated?

Every time the `network.yaml` file is edited, the sudoers file must be regenerated.
