### ISSUE TITLE
How to unset https_proxy with /etc/environment

### ISSUE THREAD

**Issue by zouchengli** [lima-vm/lima#1829]
### Description
Every time a new virtual machine is started, the proxy environment variable will be set. How to cancel it?

**Comment by jandubois** [comment]
There currently is no mechanism to unset the variable. I've created #1834 that will allow you unset them in `lima.yaml`:

```yaml
env:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
```

Or you can set them in your shell:

```shell
https_proxy="" limactl start
```
