### ISSUE TITLE
Add support for HTTP Proxy or any generic environment variables

### ISSUE THREAD

**Issue by legege** [lima-vm/lima#189]
Starting a VM when behind an HTTP Proxy doesn't work right now. There are various errors from the boot scripts.

However, adding these environment variables to `lima.env` and compiling Lima from source works:

```
...
LIMA_CIDATA_SLIRP_GATEWAY={{ .SlirpGateway }}
http_proxy=proxy_host:3128
https_proxy=proxy_host:3128
no_proxy=.internal.example.com
HTTP_PROXY=proxy_host:3128
HTTPS_PROXY=proxy_host:3128
NO_PROXY=.internal.example.com
```

One way to solve this would be to allow generic environment variables to be specified in the `lima.yaml`. Something like:

```
env:
  http_proxy: "proxy_host:3128"
  https_proxy: "proxy_host:3128"
  no_proxy: ".internal.example.com"
  HTTP_PROXY: "proxy_host:3128"
  HTTPS_PROXY: "proxy_host:3128"
  NO_PROXY: ".internal.example.com"
```

We could as well automatically add these variables to a profile file, like `/etc/profile.d/env.sh`, to make sure the variables are also in the user environment. That would avoid having to create a provision script like this one:

```
provision:
  - mode: system
    script: |
      #!/bin/bash
      echo "http_proxy=proxy_host:3128" > /etc/profile.d/proxy.sh
      echo "https_proxy=proxy_host:3128" >> /etc/profile.d/proxy.sh
      echo "no_proxy=.internal.example.com" >> /etc/profile.d/proxy.sh
      echo "HTTP_PROXY=proxy_host:3128" >> /etc/profile.d/proxy.sh
      echo "HTTPS_PROXY=proxy_host:3128" >> /etc/profile.d/proxy.sh
      echo "NO_PROXY=.internal.example.com" >> /etc/profile.d/proxy.sh
```

Let me know what you think.
