### ISSUE TITLE
not able configure custom DNS resolvers using lima 18 (using colima)

### ISSUE THREAD

**Issue by revanth-Infoworks** [lima-vm/lima#1959]
### Description

I start colima instance with --dns flag which is supposed to add dns resolvers to /etc/resolv.conf. After upgrading lima from 0.16.0 to 0.18.0, this does not seem to be working. 

colima start --vm-type vz --mount-type virtiofs --cpu 4 --memory 8 --dns 1.1.1.1 --dns 8.8.8.8

expected output:
colima:~$ cat /etc/resolv.conf
nameserver 1.1.1.1
nameserver 8.8.8.8

current output: 
colima:~$ cat /etc/resolv.conf
nameserver 192.168.5.2

my laptop configuration:
macOS Intel >= 13 (Ventura)
limactl version 0.18.0
colima version v0.5.5

Greatly appreciate any assistance on this issue.
If this is a duplicate of https://github.com/lima-vm/lima/issues/1940 please close this. 

Adding ~/.lima/colima/lima.yaml

```
`cat ~/.lima/colima/lima.yaml
vmType: vz
arch: x86_64
images:
  - location: https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.5/alpine-lima-clm-3.18.0-aarch64.iso
    arch: aarch64
    digest: sha512:84c93e8aaa09446618bf87daa993e260da69b50e95670aed5df6671b2cff9464810752cbf70f6ee5ddf9d3e1c91d98104b3c573cc024c5f0687ad3f4d2e93ebc
  - location: https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.5/alpine-lima-clm-3.18.0-x86_64.iso
    arch: x86_64
    digest: sha512:f761b807fe9ba345968df72c07f8c5abcae0c4a44976fe5595c0ff748ef693841221a70e663986c700b027cea32b7cac24d5490d4c721593c39f2b8840c362a2
cpus: 4
memory: 8GiB
disk: 60GiB
mounts:
  - location: "~"
    writable: true
  - location: /tmp/colima
    writable: true
mountType: virtiofs
containerd:
  system: false
  user: false
dns:
  - 1.1.1.1
  - 8.8.8.8
firmware:
  legacyBIOS: false
hostResolver:
  enabled: false
  hosts:
    host.docker.internal: host.lima.internal
portForwards:
  - guestPortRange:
      - 0
      - 0
    guestSocket: /var/run/docker.sock
    hostPortRange:
      - 0
      - 0
    hostSocket: /Users/infoworks/.colima/default/docker.sock
    proto: tcp
  - guestPortRange:
      - 0
      - 0
    guestSocket: /var/run/docker.sock
    hostPortRange:
      - 0
      - 0
    hostSocket: /Users/infoworks/.colima/docker.sock
    proto: tcp
  - guestIPMustBeZero: true
    guestIP: 0.0.0.0
    guestPortRange:
      - 1
      - 65535
    hostIP: 0.0.0.0
    hostPortRange:
      - 1
      - 65535
    proto: tcp
  - guestIP: 127.0.0.1
    guestPortRange:
      - 1
      - 65535
    hostIP: 127.0.0.1
    hostPortRange:
      - 1
      - 65535
    proto: tcp
provision:
  - mode: system
    script: sysctl -w fs.inotify.max_user_watches=1048576
  - mode: user
    script: sudo usermod -aG docker $USER
  - mode: system
    script: grep -q "^rc_env_allow" /etc/rc.conf || echo 'rc_env_allow="*"' >> /etc/rc.conf
  - mode: system
    script: mkmntdirs && mount -a
  - mode: system
    script: readlink /sbin/fstrim || fstrim -a
  - mode: system
    script: stat /sys/class/block/vda/queue/write_cache && echo 'write through' > /sys/class/block/vda/queue/write_cache`
```
