### ISSUE TITLE
LIMA_CIDATA_* variables aren't accessible from user mode provision script

### ISSUE THREAD

**Issue by frkd-dev** [lima-vm/lima#2051]
### Description

[Lima's environment vars](https://github.com/lima-vm/lima/blob/master/pkg/cidata/cidata.TEMPLATE.d/lima.env) are not accessible from a user mode provision script like this:

```yaml
provision:
- mode: user
  script: |
    #!/bin/sh
    ln -s $LIMA_CIDATA_HOSTHOME_MOUNTPOINT/.conan ~/.conan
```

The above script creates a wrong link since the `LIMA_CIDATA_HOSTHOME_MOUNTPOINT` variable isn't visible from the script:
```
# ls -la ~
total 20
drwxr-xr-x    4 zzzzz    zzzzz         4096 Dec  4 15:01 .
drwxr-xr-x    3 root     root          4096 Dec  2 00:02 ..
-rw-------    1 zzzzz    zzzzz          234 Dec  4 11:58 .ash_history
lrwxrwxrwx    1 zzzzz    zzzzz            7 Dec  4 15:01 .conan -> /.conan
drwxr-xr-x    3 zzzzz    zzzzz         4096 Dec  4 11:54 .config
drwx------    2 zzzzz    zzzzz         4096 Dec  2 00:02 .ssh
```
