### ISSUE TITLE
External driver, for cloud and physical

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2109]
### Description

Add a generic driver for external virtual machines and physical servers.

It is similar to running `ssh`, but includes all the Lima features like agent.

---

The user is supposed to have an existing server, with key-based ssh login.

Host keys are being used (and should be set up), to verify the external server.

A  `guest-install` command is added, to install lima-guestagent and nerdctl-full.

The external machine lifecycle (boot/reboot/etc) is managed outside of Lima.

----

* #2000
* #2028

Tested with Digital Ocean, and with Raspberry Pi.

Note: this driver does **not** create cloud instances.

**Comment by afbjorklund** [comment]
The hardware resources are specified by the user, matching the external:

```yaml
vmType: ext

arch: "aarch64"
cpus: 4
memory: 512MiB
disk: 32GiB

mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true

ssh:
  address: raspberrypi.local
```

The OS installation is supposed to be aligned, but is not using the "images".

e.g. you would use the cloud web interface or the SD card image for Ubuntu
