### ISSUE TITLE
Customizable image location property

### ISSUE THREAD

**Issue by roman-kiselenko** [lima-vm/lima#2226]
### Description

Following this issue https://github.com/abiosoft/colima/issues/995 

> This is happening because this is a work laptop and due to security reasons, I am not allowed to download it via the Terminal. I can download this file in the browser.

I just realize that this would be a good feature to have, customizable image location:

```yaml
# OpenStack-compatible disk image.
# 🟢 Builtin default: null (must be specified)
# 🔵 This file: Ubuntu images
images:
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release-20240125/ubuntu-22.04-server-cloudimg-amd64.img"
    arch: "x86_64"
    digest: "sha256:f23e5b91af7f52bdd4680d8e9d091093bfc6c4a46b0da7baa3cb450ee917b66b"
```

If for example a user have airgapped environment or some security policy and in order to run VM you can specify you own `.img`. Something like this:

```yaml
# OpenStack-compatible disk image.
# 🟢 Builtin default: null (must be specified)
# 🔵 This file: Ubuntu images
images:
  - location: "file://~/Downloads/ubuntu-22.04-server-cloudimg-amd64.img"
    arch: "x86_64"
    digest: "sha256:f23e5b91af7f52bdd4680d8e9d091093bfc6c4a46b0da7baa3cb450ee917b66b"
```

In order to achieve this functionalities all we need is a right handling of `location` property:

https://github.com/lima-vm/lima/blob/4d57ff6308ff9085d65bd5fc3a91abb74c79993e/pkg/fileutils/download.go#L17-L18

@lima-vm/maintainers WDYT?
