### ISSUE TITLE
Lima disregards settings in `networks.yaml` until explicitly specified

### ISSUE THREAD

**Issue by TibiIius** [lima-vm/lima#2281]
### Description

When trying to set up a new Lima VM (I tested using both the `docker` aswell as the `docker-rootful` template), I noticed that the network will be inside the `192.168.5.0/24` subnet. This contradicts Lima's default settings for `user-v2` network mode, which, at least in my case, looks like the following (unnecessary output is redacted):
```
~/.lima/_config
[tim@Tims-MacBook-Pro] ❯ cat networks.yaml
# ...
networks:
  user-v2:
    mode: user-v2
    gateway: 192.168.104.1
    netmask: 255.255.255.0
```
Only when editing the VM's config and including a `networks` section will the actual gateway value that's configured be used.
```
networks:
  - lima: user-v2
```

I'm not 100% certain if this is intended behavior. At the very least, I find this kind of behavior very confusing and unintuitive, and it took me quite some time figuring this out.
