### ISSUE TITLE
Simplify syntax for default mounts

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2422]
### Description

Currently this block is duplicated to most of the templates:

```yaml
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
```
