### ISSUE TITLE
Provide standard values "default" and "none" for most options

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2458]
### Description

It would be nice to be able to use simple defaults like "default".

```yaml
audio:
  # EXPERIMENTAL
  # QEMU audiodev, e.g., "none", "coreaudio", "pa", "alsa", "oss".
  # Choosing "none" will mute the audio output, and not play any sound.
  # Choosing "default" will pick the suitable of coreudio, pa, dsound.
  # 🟢 Builtin default: ""
  device: default

video:
  # QEMU display, e.g., "none", "cocoa", "sdl", "gtk", "vnc", "default".
  # Choosing "none" will hide the video output, and not show any window.
  # Choosing "default" will pick the first available of: gtk, sdl, cocoa.
  # 🟢 Builtin default: "none"
  display: default
```

Instead of having to remember gtk and pa, or vz, or whatever...

* https://github.com/lima-vm/lima/pull/990
* https://github.com/lima-vm/lima/pull/2456

Note: Vz will not support the QEMU device/driver names.
But it should still honor the "none" and "default" strings.

**Comment by afbjorklund** [comment]
Other PRs used the same ("default") also for images and mounts:

```yaml
images:
- default

mounts:
- default
```

But those are arrays, so "none" is usually just written out as `[]`.

One _could_ have the string (`"none"`) expand to the empty list?

**Comment by afbjorklund** [comment]
New syntax:

```yaml
images: []
mounts: []

base:
- template://_images/ubuntu
- template://_default/mounts
```
