### ISSUE TITLE
stuck on "Waiting for the essential requirement 1 of 4: "ssh" with non-Ubuntu and libslirp v4.6.1

### ISSUE THREAD

**Issue by LATBauerdick** [lima-vm/lima#255]
I get stuck on "Waiting for the essential requirement 1 of X: "ssh" even with libslirp v4.6.1 for non-Ubuntu guests only, both for `alpine` and for `arch linux` -- works fine with `default.yaml` and `ubuntu`. 

The initial `limactl start alpine` works, but after a `limactl stop alpine` I get stuck with a large number of messages like
```
...
INFO[0080] [hostagent] Waiting for the essential requirement 1 of 4: "ssh" 
...
```
and finally
```
...
INFO[0587] [hostagent] Waiting for the essential requirement 1 of 4: "ssh" 
INFO[0597] [hostagent] Waiting for the essential requirement 1 of 4: "ssh" 
INFO[0597] [hostagent] Waiting for the essential requirement 2 of 4: "sshfs binary to be installed" 
FATA[0601] did not receive an event with the "running" status  
```
again, Ubuntu and `default.yaml` work just fine.

**Comment by jandubois** [comment]
Which lima version did you use? A number of people ran into problems because they had user names that did not work properly on all Linux systems, e.g containing a dot `firstName.lastName`, email address: `me@company.com`, all numeric: `12345678`. In Lima 0.6.4 we are mapping all names that don't match the rather strict rules of `useradd` from the `shadow` package to a default name of `lima` to avoid these issues.

So if you have been using an earlier Lima version, please update and see if that fixes your problem. And if you created your own `alpine.yaml`, please update that as well to use the latest ISO image, as some issues have been fixed in there as well (e.g. having a uid on macOS > 25600).

**Comment by LATBauerdick** [comment]
I just installed lima from brew: `limactl version 0.6.4`

username is `bauerdic`, so that should be ok.

`alpine.yaml` is from the head.

**Comment by jandubois** [comment]
Could you follow the instructions from https://github.com/rancher-sandbox/rancher-desktop/issues/562#issuecomment-910779740 (in spirit, the directory with the socket will be `~/.lima/alpine`), to log into the Alpine VM while lima is still waiting for ssh to come up, and collect the output from `sudo cat /var/log/lima-init.log` and append it to this bug?

Whew, run-on-sentences-are-us! 😄

**Comment by LATBauerdick** [comment]
```
lima-alpine:~# ^[[53;16Rcat /mnt/lima-cidata/user-data
cat /mnt/lima-cidata/user-data
#cloud-config
# vim:syntax=yaml

growpart:
  mode: auto
  devices: ['/']

users:
  - name: "bauerdic"
    uid: "6170"
    homedir: "/home/bauerdic.linux"
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKSfQOtfNmJm98lw8t7SRynbbgZhK+22Oy4syAAzvSLv bauerdic@lmini.local"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJOXZjedCEONef8tQoqk8iZYODg0VoONlyfIz5tFfWXz bauerdic@lmini.local"

write_files:
 - content: |
      #!/bin/sh
      set -eux
      LIMA_CIDATA_MNT="/mnt/lima-cidata"
      LIMA_CIDATA_DEV="/dev/disk/by-label/cidata"
      mkdir -p -m 700 "${LIMA_CIDATA_MNT}"
      mount -o ro,mode=0700,dmode=0700,overriderockperm,exec,uid=0 "${LIMA_CIDATA_DEV}" "${LIMA_CIDATA_MNT}"
      export LIMA_CIDATA_MNT
      exec "${LIMA_CIDATA_MNT}"/boot.sh
   owner: root:root
   path: /var/lib/cloud/scripts/per-boot/00-lima.boot.sh
   permissions: '0755'
# This has no effect on systems using systemd-resolved, but is used
# on e.g. Alpine to set up /etc/resolv.conf on first boot.

manage_resolv_conf: true

resolv_conf:
  nameservers:
  - 191.68.0.142
  - 192.168.0.1
  - 192.168.5.3
```
