### ISSUE TITLE
Basic yaml templating support

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#2804]
### Description

It would be nice if the templates could support basic preprocessing such as includes and variables.

One such templating engine is https://github.com/con2/emrichen, that uses YAML for the template.

ubuntu.in.yaml:
```yaml
# This template requires Lima v0.7.0 or later.
images: !Include images.yaml
mounts: !Include mounts.yaml
```
Local variables:
```yaml
!Defaults
var1: default1
var2: default2
---
var1: !Var var1
var2: !Var var2
```

You can still use `yq` for editing the document in-place (like before), either the template or the result.

Other alternatives require some input format that is almost-but-not-quite actual YAML (yamllint):

* jinja2
* cpphash
