### ISSUE TITLE
portForwards ignore not respected without guestIP: "0.0.0.0"

### ISSUE THREAD

**Issue by nirs** [lima-vm/lima#2901]
### Description

In lima 1.0.0 we could disable port forwarding (except ssh port) using:

```yaml
portForwards:
  - ignore: true
    proto: any 
```

In lima 1.0.1 this seems to be broken. The port rule is detected, but then we see logs about port forwarding.

```
% limactl start --tty=0 test.yaml
...
INFO[0012] [hostagent] TCP (except for SSH) and UDP port forwarding is disabled 
...
INFO[0089] [hostagent] Forwarding TCP from [::]:10250 to 127.0.0.1:10250 
INFO[0092] [hostagent] Forwarding TCP from [::]:6443 to 127.0.0.1:6443 
```

I think this is the change in 1.0.1 to disable the grpc port forwarding. The ignore rule probably never worked with the ssh forwarder.

Can be reproduced by this k8s based yaml:
[test.tar.gz](https://github.com/user-attachments/files/17738230/test.tar.gz)

**Comment by jandubois** [comment]
> The ignore rule probably never worked with the ssh forwarder.

I've not tested it, but just looked at the source, and it has been implemented in a similar way for the ssh forwarder as well. Not sure why it doesn't work.

**Comment by nirs** [comment]
Before we switched to grpc, I used a different rule that worked:

```yaml
portForwards:
  - guestPortRange: [1, 65535]
    guestIP: "0.0.0.0"
    ignore: true
```

**Comment by nirs** [comment]
Adding guestIP solves the issue:

```yaml
portForwards:
  - ignore: true
    proto: any 
    guestIP: "0.0.0.0"
```
