### ISSUE TITLE
`limactl start --plain` does not create `/etc/subuid` on macOS hosts (but creates on Linux hosts)

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#3001]
macOS 15.1.1 (x86_64, tried both vz and QEMU)
```console
$ limactl -v
limactl version 1.0.2
$ limactl start --plain
$ limactl shell default cat /etc/subuid
(empty)
```

Ubuntu 24.10 (x86_64)
```console
$ limactl -v
limactl version 1.0.2
$ limactl start --plain
$ limactl shell default cat /etc/subuid
suda:100000:65536
```

Found in:
- https://github.com/rootless-containers/usernetes/issues/348

**Comment by AkihiroSuda** [comment]
`/mnt/lma-cidata/user-data` slightly differs across macOS and Linux.

macOS:
```
users:                                                     
  - name: "suda"      
    uid: "501"                                                                                                         
    gecos: "Akihiro Suda"                                  
    homedir: "/home/suda.linux"
    shell: /bin/bash    
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
[...]
```

Linux:
```
users:                                                                                                                                     
  - name: "suda"                                                                                                                           
    uid: "1001"                                                                                                                            
    homedir: "/home/suda.linux"                                                                                                            
    shell: /bin/bash                                                 
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true                                                
    ssh-authorized-keys:
[...]
```

Probably related to GECOS?
