### ISSUE TITLE
vz driver is running but host agent is not

### ISSUE THREAD

**Issue by houserockr** [lima-vm/lima#3081]
### Description

After upgrading my lima installation via homebrew to version 1.0.3, my vm stopped working.

```
$ brew upgrade lima
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: lima 1.0.3 already installed
```

```
$ limactl -v
limactl version 1.0.3
```

This is the error I'm getting:

```
$ limactl start foo
INFO[0000] Using the existing instance "foo"            
FATA[0000] errors inspecting instance: [vz driver is running but host agent is not] 
```
Pruning cache doesn't help either
```
$ limactl prune
INFO[0000] Pruning "/Users/user/Library/Caches/lima"
```

```
$ limactl start foo
INFO[0000] Using the existing instance "foo"            
FATA[0000] errors inspecting instance: [vz driver is running but host agent is not]
```

vm's config

```
images:
  - location: "https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-amd64-20240717-1811.qcow2"
    arch: "x86_64"
    digest: "sha512:0f0075d53749dba4c9825e606899360626bb20ac6bab3dbdeff40041b051d203eb1a56e68d377c9fac0187faa0aea77fd543ef4a883fff2304eac252cce01b44"
  - location: "https://cloud.debian.org/images/cloud/bookworm/20240717-1811/debian-12-genericcloud-arm64-20240717-1811.qcow2"
    arch: "aarch64"
    digest: "sha512:a68fe32c459d6d33cd8f6798fe7e2278d32add2b9506f4a6c434328a0a9cd176e532a93d0184173720023db5edfd93061082fadcb91bb3e95988564c63f139a6"
  - location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
    arch: "x86_64"
  - location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2"
    arch: "aarch64"
vmType: "vz"
cpus: 8
memory: 8GiB
rosetta:
  enabled: true
networks:
- vzNAT: true
mountType: "virtiofs"
mounts:
  - location: "~"
    writable: true
  - location: "/tmp/lima"
    writable: true
additionalDisks:
  - name: "rawdisk"
    format: true
    fsType: "ext4"
```

OS is MacOS Sequoia 15.2
