### ISSUE TITLE
crash when connecting to VM

### ISSUE THREAD

**Issue by shenki** [lima-vm/lima#3172]
### Description

When I added a snippet to `~/.lima/default/lima.yml` and tried to connect:

```
$ lima --version
limactl version 1.0.4
$ lima
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x80 pc=0x10351e494]

goroutine 1 [running]:
main.shellAction(0x14000156c08, {0x14000114ed0?, 0x4?, 0x103537de5?})
	/private/tmp/lima-20250121-4853-uuipyh/lima-1.0.4/cmd/limactl/shell.go:90 +0x3c4
github.com/spf13/cobra.(*Command).execute(0x14000156c08, {0x14000114ea0, 0x1, 0x1})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x14000156008)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
	/private/tmp/lima-20250121-4853-uuipyh/lima-1.0.4/cmd/limactl/main.go:28 +0x20
```

The snippet I added was:
```
ssh:
- forwardAgent: true
```

I (now) realise the syntax is incorrect, but it would be better if the tool didn't crash

**Comment by AkihiroSuda** [comment]
Thanks for the report.
Seems a duplicate of #3103

**Comment by jandubois** [comment]
@shenki Can you please show the exact change you made? I cannot reproduce the problem; it always gets caught by YAML validation:

If I simply add the snippet:

```
FATA[0023] failed to unmarshal YAML (main file "/Users/jan/.lima/default/lima.yaml"): [145:1] mapping key "ssh" already defined at [7:1]
> 145 | ssh:
        ^
  146 |   # A localhost port of the host. Forwarded to port 22 of the guest.
  147 |   # 🟢 Builtin default: 0 (automatically assigned to a free port)
  148 |   # NOTE: when the instance name is "default", the builtin default value is set to
  149 |
```

If I add the snippet under the existing `ssh` key:

```
FATA[0029] failed to unmarshal YAML (main file "/Users/jan/.lima/default/lima.yaml"): [162:3] mapping key "forwardAgent" already defined at [145:3]
  159 |   # Set the environment variable `SSH_AUTH_SOCK` value to the path above.
  160 |   # The socket is accessible by the non-root user inside the Lima instance.
  161 |   # 🟢 Builtin default: false
> 162 |   forwardAgent: null
          ^
  163 |   # Forward X11 into the instance
  164 |   # 🟢 Builtin default: false
  165 |   forwardX11: null
  166 |
```

If I replace the existing `ssh` key and everything below it:

```
FATA[0028] failed to unmarshal YAML (main file "/Users/jan/.lima/default/lima.yaml"): [145:1] sequence was used where mapping is expected
  144 | ssh:
> 145 | - forwardAgent: true
        ^
  147 | caCerts:
  148 |   # If set to `true`, this will remove all the default trusted CA certificates that
  149 |
```

**Comment by shenki** [comment]
This was my yaml before:

```
# This template requires Lima v0.7.0 or later
images:
- location: "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-genericcloud-amd64-daily.qcow2"
  arch: "x86_64"
- location: "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-genericcloud-arm64-daily.qcow2"
  arch: "aarch64"
mountTypesUnsupported: ["9p"]
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
memory: 16GiB
cpus: 14
```

Here it is after:
```
# This template requires Lima v0.7.0 or later
images:
- location: "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-genericcloud-amd64-daily.qcow2"
  arch: "x86_64"
- location: "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-genericcloud-arm64-daily.qcow2"
  arch: "aarch64"
mountTypesUnsupported: ["9p"]
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
memory: 16GiB
cpus: 14
ssh:
 forwardAgent: true
```

I wasn't aware that `lamactrl edit` existed, so I was editing the file and then running `lama`. The vm was running the entire time, as I was unaware that I needed to stop and start the vm, but just running `lama` was enough to parse the yaml and trigger the crash.
