### ISSUE TITLE
New subproject: `lima-actions` (Lima on GitHub Actions)

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#3312]
@lima-vm/maintainers 

Let me move https://github.com/AkihiroSuda/lima-actions to https://github.com/lima-vm .

Useful for running non-Ubuntu distributions such as Fedora on GHA.

```yaml
steps:
  - uses: actions/checkout@v4

  - uses: lima-vm/lima-actions/setup@v1
    id: lima-actions-setup

  - uses: actions/cache@v4
    with:
      path: ~/.cache/lima
      key: lima-${{ steps.lima-actions-setup.outputs.version }}

  - run: limactl start --plain --name=default --cpus=1 --memory=1 template://fedora

  - uses: lima-vm/lima-actions/ssh@v1

  - run: rsync -a -e ssh . lima-default:/tmp/repo

  - run: ssh lima-default ls -l /tmp/repo
```
