### ISSUE TITLE
Incorrect warning: `vmType vz: ignoring images[0]: [Kernel Initrd] `

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#3341]
The vz driver prints `vmType vz: ignoring images[0]: [Kernel Initrd] ` when a custom kernel is specified, even though it is not actually ignored.

e.g.,
```yaml
images:
- location: "https://cloud-images.ubuntu.com/plucky/20250310/plucky-server-cloudimg-amd64.img"
  arch: "x86_64"
  kernel:
    location: https://cloud-images.ubuntu.com/plucky/20250310/unpacked/plucky-server-cloudimg-amd64-vmlinuz-generic
    digest: sha256:547c4316eadc8e46b043b5658fd4c08d62b3522c07a7eb94692e1b7d8827bf52
    cmdline: root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyAMA0 nopku
  initrd:
    location: https://cloud-images.ubuntu.com/plucky/20250310/unpacked/plucky-server-cloudimg-amd64-initrd-generic
    digest: sha256:2842bb61052f77c1f1301394c5db215e3d89696b122accd42b7a7b30ae0c64d4
```
