### ISSUE TITLE
Embedding a larger binary file doesn't work

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#3403]
We can now embed data provision files:

```yaml
provision:
- mode: data
  file: binary.data
  path: /tmp/binary.data
```

But if the data file is long, this throws an error:

```
FATA[0000] Feature Retain Line Breaks BeforeAction failed with error: bufio.Scanner: token too long
```

This could probably be fixed by embedding the binary blob as a base64 encoded string using the `!!binary` tag.
