### ISSUE TITLE
Lima fails to run, if deleting all the git tags before building

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/lima#3495]
### Description

It chokes on the generated version, during validate:

`FATA[0001] the YAML is invalid, saved the buffer as "lima.REJECTED.yaml": can't parse builtin Lima version "edec9bc1": edec9bc1 is not in dotted-tri format`

It probably shouldn't generate an invalid version...

```Makefile
VERSION := $(shell git describe --match 'v[0-9]*' --dirty='.m' --always --tags)
```

**Comment by afbjorklund** [comment]
There is some workaround for this in the GitHub actions:

```yaml
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        # To avoid "failed to load YAML file \"templates/experimental/riscv64.yaml\": can't parse builtin Lima version \"3f3a6f6\": 3f3a6f6 is not in dotted-tri format"
        fetch-depth: 0
```

commit 762e5108658a38f8e8e94104cccc5778b17fef88 - to avoid shallow clones, without tags
