### ISSUE TITLE
Run qemu-guest-agent to keep time in sync with host?

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#355]
There has been a question about containers falling behind in time when the host has been suspended: https://github.com/rancher-sandbox/rancher-desktop/discussions/836

I believe this would be fixed by installing the `qemu-guest-agent`, but haven't tested it (because I'm not sure how to set it up, but I've only looked at Alpine so far).

**Comment by totallyGreg** [comment]
I would like to be be able to do this so shutdowns are communicated properly and various stats are provided.  I've had success installing the qemu-guest-agent in a k3os image running on proxmox, by adding this to the cloud-config file. 
```
write_files:
- path: /etc/conf.d/qemu-guest-agent
  content: |-
    # Specifies the transport method used to communicate to QEMU on the host side
    # Default: virtio-serial
    #GA_METHOD="virtio-serial"
    # Specifies the device path for the communications back to QEMU on the host
    # Default: /dev/virtio-ports/org.qemu.guest_agent.0
    #GA_PATH="/dev/virtio-ports/org.qemu.guest_agent.0"
      GA_PATH=/dev/vport2p1
  owner: root
  permissions: '0644'
```
I am not sure how lima is communicating with qemu but if the device port  path is known I can try it out.
