### ISSUE TITLE
Stuck network when using multiple connections with k3s

### ISSUE THREAD

**Issue by JanPokorny** [lima-vm/lima#3601]
# Summary

When running a non-trivial web app in a Lima VM using the `k3s` template, the network stops being responsive. This seems to happen when multiple persistent HTTP connections are established. With non-trivial web apps which load many resources, this can be triggered by simply opening the app in two tabs at once.

# Reproduction

1. Prepare these files (somewhere under your `~`):

Dockerfile
```Dockerfile
FROM python:3.11-slim

ARG CSS_COUNT=1000
ENV CSS_COUNT=${CSS_COUNT}

WORKDIR /app

RUN cat <<EOF >main.py
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

class NoCacheStaticFiles(StaticFiles):
    async def get_response(self, path: str, scope):
        response = await super().get_response(path, scope)
        response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
        return response

app = FastAPI()
app.mount("/", NoCacheStaticFiles(directory="static", html=True), name="static")
EOF

RUN mkdir static

RUN echo '<!DOCTYPE html>' > static/index.html && \
    echo '<html><head><title>Test Lima Port Bug</title>' >> static/index.html && \
    for i in $(seq 0 $((${CSS_COUNT} - 1))); do \
        echo "  <link rel=\"stylesheet\" href=\"$i.css\">" >> static/index.html; \
    done && \
    echo '</head><body><h1>Hello from FastAPI static site!</h1></body></html>' >> static/index.html

RUN for i in $(seq 0 $((${CSS_COUNT} - 1))); do \
        echo -n "/* " > static/$i.css && \
        head -c 500000 /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 80 | head -n 100 >> static/$i.css && \
        echo " */" >> static/$i.css; \
    done

RUN pip install fastapi uvicorn

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

k8s.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: repro-service
spec:
  type: NodePort
  selector:
    app: repro
  ports:
    - port: 8000
      nodePort: 31833
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-repro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repro
  template:
    metadata:
      labels:
        app: repro
    spec:
      containers:
        - name: repro
          image: repro:local
          ports:
            - containerPort: 8000
```

2. Build image and start the server (this needs a local `docker` CLI to build the image, I use Colima, it probably does not matter):
```bash
docker build -t repro:local .
docker save repro:local >repro.tar
limactl --tty=false start template://k3s --name=repro --mount=~
limactl --tty=false shell repro -- sudo ctr images import repro.tar
limactl --tty=false shell repro -- kubectl apply -f k8s.yaml
```

3. Open `http://localhost:31833/` in browser. It will load just fine the first time. Leave the tab open and open `http://localhost:31833/` in another tab. Repeat and open a few tabs like this, until you'll notice that the page stops loading, being stuck in a "pending" state. The stuck pages will sometimes load eventually after 20s or so, some will time out.

# What I discovered

It appears that the new tabs are unable to establish TCP connections to the application. This seems to be related to the number of existing HTTP persistent connections (`Connection: keep-alive`). When I force `Connection: close` in the server, the problem disappears. And it's the reason why the bug only manifests when multiple tabs are open, as browsers hold separate connections per tab. The huge number of dummy CSSs is there just to force the browser to open the max number of connections.

Notably this bug does not happen when using `kubectl port-forward` instead of the NodePort, so the problem is somewhere in the Lima networking stack or perhaps the way it interacts with the k3s networking stack.

# Versions
macOS 15.5 (24F74)
limactl version 1.1.1 (installed from Homebrew)
happens on both VZ and QEMU VMs
