### ISSUE TITLE
What is dangerous about mounting home writeable?

### ISSUE THREAD

**Issue by tmewett** [lima-vm/lima#449]
In the default config, there is:

```yaml
mounts:
  - location: "~"
    # CAUTION: `writable` SHOULD be false for the home directory.
    # Setting `writable` to true is possible, but untested and dangerous.
    writable: false
```

I was wondering what kinds of failure modes we should expect from a writeable home, and if any data loss has ever been observed. It would help users evaluate the risks. E.g. am I only worried about individual files being corrupted if errors occur? Or my entire home being deleted by some freak mounting issue? I appreciate this may deliberately err on the side of caution and failures are not well-known, but any info would be great. Thank you :)
