### ISSUE TITLE
Cannot mount volumes on stock Postgres image

### ISSUE THREAD

**Issue by tragiclifestories** [lima-vm/lima#504]
Hi! Just playing around with Lima for the first time and having trouble mounting directories using the stock Postgres image - raising here since it doesn't look like Postgres is doing anything too wild so it may be a lima bug?

## Reproduction

```bash
mkdir -p /tmp/lima/pgdata
lima nerdctl run -v "/tmp/lima/pgdata:/var/lib/postgresql/data" postgres:13
#=> chown: changing ownership of '/var/lib/postgresql/data': Permission denied
```

Looking at the [postgres dockerfile](https://github.com/docker-library/postgres/blob/3bb48045b4dc5df24bf2271c679f7a4e9efcbe6e/13/bullseye/Dockerfile#L179-L182), it creates the directory and CHOWNs it, and then declares the `VOLUME` afterwards - nothing else in the file seems immediately relevant.

Lima version 0.8.0

Mounts in `lima.yaml`: 

```yaml
# Expose host directories to the guest, the mount point might be accessible from all UIDs in the guest
# Default: none
mounts:
  - location: "~/Projects"
    # CAUTION: `writable` SHOULD be false for the home directory.
    # Setting `writable` to true is possible, but untested and dangerous.
    writable: true
  - location: "/tmp/lima"
    writable: true
```
