### ISSUE TITLE
can not download some libs from ubuntu

### ISSUE THREAD

**Issue by fungbo** [lima-vm/lima#544]
please find the error logs below:

[   27.446390] cloud-init[929]: Ign:1 http://archive.ubuntu.com/ubuntu impish/universe amd64 libfuse3-3 amd64 3.10.3-2
[   27.576045] cloud-init[929]: Ign:2 http://archive.ubuntu.com/ubuntu impish/universe amd64 fuse3 amd64 3.10.3-2
[   29.584675] cloud-init[929]: Ign:1 http://archive.ubuntu.com/ubuntu impish/universe amd64 libfuse3-3 amd64 3.10.3-2
[   30.164695] cloud-init[929]: Ign:2 http://archive.ubuntu.com/ubuntu impish/universe amd64 fuse3 amd64 3.10.3-2
**[   33.920850] cloud-init[929]: Err:1 http://archive.ubuntu.com/ubuntu impish/universe amd64 libfuse3-3 amd64 3.10.3-2
[   33.923462] cloud-init[929]:   Connection failed [IP: 91.189.88.152 80]
[   34.289700] cloud-init[929]: Err:2 http://archive.ubuntu.com/ubuntu impish/universe amd64 fuse3 amd64 3.10.3-2
[   34.289831] cloud-init[929]:   Connection failed [IP: 91.189.88.152 80]
[   34.329424] cloud-init[929]: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/fuse3/libfuse3-3_3.10.3-2_amd64.deb  Connection failed [IP: 91.189.88.152 80]
[   34.329537] cloud-init[929]: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/fuse3/fuse3_3.10.3-2_amd64.deb  Connection failed [IP: 91.189.88.152 80]
[   34.329858] cloud-init[929]: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?**
[   34.330350] cloud-init[929]: LIMA| WARNING: Failed to execute /mnt/lima-cidata/boot/30-install-packages.sh
[   34.330717] cloud-init[929]: LIMA| Executing /mnt/lima-cidata/boot/40-install-containerd.sh
[   34.346595] cloud-init[929]: + [  != 1 ]

The process was stuck at [hostagent] Waiting for the essential requirement 4 of 5: "/etc/fuse.conf to contain \"user_allow_other\""

So can I change the ubuntu source list? If yes, how to do that?

Thanks

**Comment by fungbo** [comment]
Tried many times, it's working when I run limactl start docker.yaml, still failed to run limactl start

**Comment by AkihiroSuda** [comment]
Is this related to GFW?

Could you try modifying `/etc/apt/*` with `limactl shell docker`, and then `limactl stop docker`, `limactl start docker`?

**Comment by zinking** [comment]
+1 here, don't think it's gfw related, could ping on mac shell.

**Comment by yanyixing** [comment]
You can try to use the fedora image, fedora can use the nearest pkg source automatically.

fedora.yaml

```
# This example requires Lima v0.7.0 or later.
images:
- location: "https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-35-1.2.x86_64.qcow2"
  arch: "x86_64"
  digest: "sha256:fe84502779b3477284a8d4c86731f642ca10dd3984d2b5eccdf82630a9ca2de6"
- location: "https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/aarch64/images/Fedora-Cloud-Base-35-1.2.aarch64.qcow2"
  arch: "aarch64"
  digest: "sha256:c71f2e6ce75b516d565e2c297ea9994c69b946cb3eaa0a4bbea400dbd6f59ae6"
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
```

```
limactl start fedora.yaml

export LIMA_INSTANCE=fedora

alias docker="lima nerdctl"

docker images
```
