### ISSUE TITLE
add buildkit.yaml to examples

### ISSUE THREAD

**Issue by developer-guy** [lima-vm/lima#567]
We've developed a tool called buildkit-machine that allows to forward sock or open a TCP to sock to let macOS users can access buildkitd easily without running buildkitd in a container. Then, we noticed that there is an alternative way of doing that as lima did for docker sock like the following:

```YAML
portForwards:
- guestSocket: "/run/user/{{.UID}}/docker.sock"
  hostSocket: "{{.Dir}}/sock/docker.sock"
```
> https://github.com/lima-vm/lima/blob/2b6db749c5ee63f758741e0891f1915978611b16/examples/docker.yaml#L59-L61

So, AFAIK, lima also runs the buildkitd in a rootles way which means that users may access it through /run/user/{{.UID}}/buildkit/buildkitd.sock. What we are proposing is that we can add a file to the examples folder for the buildkit to achieve the same thing.

<details>

<summary> buildkit.yaml </summary>

```YAML
portForwards:
- guestSocket: "/run/user/{{.UID}}/buildkit/buildkitd.sock"
  hostSocket: "{{.Dir}}/buildkitd.sock"
```
</details>

```shell
$  buildctl --addr unix:///Users/batuhan.apaydin/.lima/buildkit/buildkitd.sock \
   build \
    --frontend=dockerfile.v0 \
    --local context=. \
    --local dockerfile=. \
    --output type=image,name=docker.io/devopps/hello-world-buildctl,push=true
```
