### ISSUE TITLE
Provisioning should allow files and directories to be copied 

### ISSUE THREAD

**Issue by tpoindex** [lima-vm/lima#594]
### Description

I ran into a slight problem trying to provision a VM with k3s.yaml from the examples.    The provision script executes 'curl', (and subsequently the get.k3s.io script does too), but fails in my environment due to http proxy certificates not installed.    I was able to make this work by modifying the provision script to first create a /root/.curlrc file containing "--insecure --location-trusted".   This could be avoided if I could install a .curlrc or better still, TLS certificates, during provisioning.  Unfortunately, different Linux distributions install certificates in different locations, and use different scripts to update the master certs file.

I'm thinking of a more generalized method for this: - allow files and directories to be copied into the VM before the provisioning scripts run.  If a source specifies a directory, it should be copied recursively.  Source files/directories may be relative or absolute paths.  Target directories in the VM should be absolute paths.  

This would allow things like a .curlrc file, and directory containing certificates, whatever to be available to the provisioning script.

Proposed yaml syntax:
```
provision:
- copy: 
  - required: true
    source: ~/.lima/certs/
    destination: /path/in/vm
  - required: false
    source: vm-curl.rc
    destination: /root/.curlrc
- mode: system
  script: |
    #!/bin/sh
    curl -sfL https://get.k3s.io | sh -
```

Something like this could be included in the override.yaml to perform this for all provisioned VMs.
