### ISSUE TITLE
Wrong buildkit guestSocket path in template

### ISSUE THREAD

**Issue by tdaniely-dn** [lima-vm/lima#802]
### Description

Not sure what changed where, I'm not very familiar with the internals of this project.

Recently trying to use limactl buildkit, I got this error.
```
❯ buildctl debug workers
error: failed to list workers: Unavailable: connection closed before server preface received
```

Short investigation revealed that inside the vm the buildkit command line is:
```sh
buildkitd --addr=unix:///run/user/503/buildkit-default/buildkitd.sock ...
```

While the example template has:
```yaml
portForwards:
- guestSocket: "/run/user/{{.UID}}/buildkit/buildkitd.sock"
  hostSocket: "{{.Dir}}/sock/buildkitd.sock"
```

Updating the guestSocket fixed the issue.

limactl version 0.9.2
macOS Monterey 12.2.1
Darwin 21.3.0
