### ISSUE TITLE
Support archived source images

### ISSUE THREAD

**Issue by sergelogvinov** [lima-vm/lima#809]
### Description

Currently you can use only raw source images

```yaml
images:
- location: "http://domain/image.qcow2"
  arch: "x86_64"
  digest: "sha512:123123"
```

Sometimes OS distributive does not have unarchived images on the website. It will be nice to have such capabilities to use archived source images.
