### ISSUE TITLE
Ubuntu 22.04 - automated port forward not working.

### ISSUE THREAD

**Issue by marcinkubica** [lima-vm/lima#812]
### Description

Hello, and thanks for making lima a great project.

I'm using ubuntu with microk8s under lima and noticed automatic port forwarding doesn't work anymore under 22.04

My config:
```
arch: "x86_64"
name: "default"

images:
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"

cpus: 4
memory: "4GiB"
disk: "100GiB"

mounts:
- location: "~"
  writeable: false
```

Cheers
Marcin
