### ISSUE TITLE
symlinks does not work in mountType 9p

### ISSUE THREAD

**Issue by patryk4815** [lima-vm/lima#829]
### Description

Symlinks does not work in mountType 9p

`limactl version 0.10.0`

config:
```
mounts:
- location: "~"
  9p:
    # Try choosing "mmap" or "none" if you see a stability issue with the default "fscache".
    cache: "fscache"
- location: "/tmp/lima"
  writable: true
  9p:
    cache: "mmap"

mountType: "9p"
```

mount:
```
mount0 on /Users/user type 9p (ro,relatime,dirsync,fscache,access=client,trans=virtio)
```

inside vm
```
[root@nixos:/Users/user/nixpkgs]# ls -al pkgs/development/libraries/readline/update-patch-set.sh
ls: cannot read symbolic link 'pkgs/development/libraries/readline/update-patch-set.sh': Timer expired
lrwxr-xr-x 1 user lp 40 Apr 28 21:04 pkgs/development/libraries/readline/update-patch-set.sh

[root@nixos:/Users/user/nixpkgs]# cat pkgs/development/libraries/readline/update-patch-set.sh
cat: pkgs/development/libraries/readline/update-patch-set.sh: Timer expired
```

host:
```
user@hostname nixpkgs % ls -al /Users/user/nixpkgs/pkgs/development/libraries/readline/update-patch-set.sh
lrwxr-xr-x  1 user  staff  40 28 kwi 23:04 /Users/user/nixpkgs/pkgs/development/libraries/readline/update-patch-set.sh -> ../../../shells/bash/update-patch-set.sh
```
