### ISSUE TITLE
"Network dropped connection on reset" errors on 9p mounts

### ISSUE THREAD

**Issue by carletes** [lima-vm/lima#831]
### Description

Hi! Not sure whether this is a bug or not, so I'm reporting it here just in case (and thanks a lot for all your work in this project, by the way!)

Running on an M1 MackBook on macOS Monterey 12.3.1 (21E258), with the following versions of lima and QEMU (installed from Nixpkgs):

```
$ lima --version
limactl version 0.10.0
$ qemu-system-aarch64 --version
QEMU emulator version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

I see those network reset errors when doing things like this:

```
$ limactl shell docker ls -l /Users/carlos
ls: /Users/carlos: Network dropped connection on reset
ls: /Users/carlos/Music: Network dropped connection on reset
ls: /Users/carlos/Pictures: Network dropped connection on reset
ls: /Users/carlos/Desktop: Network dropped connection on reset
ls: /Users/carlos/Library: Network dropped connection on reset
ls: /Users/carlos/Public: Network dropped connection on reset
ls: /Users/carlos/Movies: Network dropped connection on reset
ls: /Users/carlos/Applications: Network dropped connection on reset
ls: /Users/carlos/Dropbox: Network dropped connection on reset
ls: /Users/carlos/Maildir: Network dropped connection on reset
ls: /Users/carlos/Documents: Network dropped connection on reset
ls: /Users/carlos/Downloads: Network dropped connection on reset
total 0
drwx------   5 carlos dialout  160 Dec  6 10:31  Applications
drwx------   4 carlos dialout  128 Apr 28 14:40  Desktop
drwx------  12 carlos dialout  384 Apr 30 08:44  Documents
drwx------ 164 carlos dialout 5248 Apr 29 13:50  Downloads
drwx------   8 carlos dialout  256 Sep  4  2021  Dropbox
drwx------  82 carlos dialout 2624 Apr  8 14:05  Library
drwxr-xr-x   3 carlos dialout   96 Nov 12 12:28  Maildir
drwx------   4 carlos dialout  128 Jul 19  2021  Movies
drwx------   4 carlos dialout  128 Aug 19  2021  Music
drwx------   4 carlos dialout  128 Jul 19  2021  Pictures
drwxr-xr-x   4 carlos dialout  128 Jul 19  2021  Public
```

The errors seem to happen in the `lgetxattr` system call:

```
$ limactl shell docker strace -f ls -l /Users/carlos
[..]
statx(AT_FDCWD, "/Users/carlos/Downloads", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_MODE|STATX_NLINK|STATX_UID|STATX_GID|STATX_MTIME|STATX_SIZE, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=5248, ...}) = 0
lgetxattr("/Users/carlos/Downloads", "security.selinux", 0xaaaaec72da70, 255) = -1 ENETRESET (Network dropped connection on reset)
write(2, "ls: ", 4ls: )                     = 4
write(2, "/Users/carlos/Downloads", 23/Users/carlos/Downloads) = 23
write(2, ": Network dropped connection on "..., 37: Network dropped connection on reset) = 37
[..]
```

I'm running with `9p2000.L` protocol version and `mapped-xattr` security model (I've tried with the other security models, too, but I get the same results). My full template follows:

```yaml
---
containerd:
  system: false
  user: false

cpus: 1

images:
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
    arch: "aarch64"

memory: 3GiB

mounts:
  - location: "~"
    writable: false
    9p:
      securityModel: mapped-xattr
      protocolVersion: 9p2000.L
      msize: 128KiB

mountType: 9p

portForwards:
  - guestSocket: "/run/user/{{.UID}}/docker.sock"
    hostSocket: "{{.Dir}}/sock/docker.sock"

probes:
  - script: |
      #!/bin/bash
      set -eux -o pipefail
      if ! timeout 30s bash -c "until command -v docker >/dev/null 2>&1; do sleep 3; done"; then
        echo >&2 "docker is not installed yet"
        exit 1
      fi
      if ! timeout 30s bash -c "until pgrep rootlesskit; do sleep 3; done"; then
        echo >&2 "rootlesskit (used by rootless docker) is not running"
        exit 1
      fi
    hint: See "/var/log/cloud-init-output.log". in the guest

provision:
  - mode: system
    script: |
      #!/bin/sh
      sed -i 's/host.lima.internal.*/host.lima.internal host.docker.internal/' /etc/hosts

  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      command -v docker >/dev/null 2>&1 && exit 0
      export DEBIAN_FRONTEND=noninteractive
      curl -fsSL https://get.docker.com | sh
      # NOTE: you may remove the lines below, if you prefer to use rootful docker, not rootless
      systemctl disable --now docker
      apt-get install -y uidmap dbus-user-session

  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      systemctl --user start dbus
      dockerd-rootless-setuptool.sh install
      docker context use rootless
```

Any idea on what might be causing this?
