### ISSUE TITLE
permission denied on shudders file

### ISSUE THREAD

**Issue by longwuyuan** [lima-vm/lima#837]
### Description

Hi,

There are no words to express the gratitude for this project and the value it brings.

I am unable to start a vmnet instance.

I have installed vde_vmnet ;
```
% ls -l /opt/vde/
total 0
drwxr-xr-x  15 root  wheel  480 May  1 13:11 bin
drwxr-xr-x   3 root  wheel   96 May  1 13:11 etc
drwxr-xr-x   7 root  wheel  224 May  1 13:11 include
drwxr-xr-x  19 root  wheel  608 May  1 13:11 lib
drwxr-xr-x   3 root  wheel   96 May  1 13:11 share
m@mypc [~] 
% ls -l /opt/vde/bin
total 1576
-rwxr-xr-x  1 root  wheel   50672 May  1 13:11 dpipe
-rwxr-xr-x  1 root  wheel   52024 May  1 13:11 unixcmd
-rwxr-xr-x  1 root  wheel   72216 May  1 13:11 vde_autolink
-rwxr-xr-x  1 root  wheel   55144 May  1 13:11 vde_over_ns
-rwxr-xr-x  1 root  wheel   52576 May  1 13:11 vde_pcapplug
-rwxr-xr-x  1 root  wheel   52728 May  1 13:11 vde_plug
-rwxr-xr-x  1 root  wheel   52744 May  1 13:11 vde_plug2tap
-rwxr-xr-x  1 root  wheel  108304 May  1 13:11 vde_router
-rwxr-xr-x  1 root  wheel  111072 May  1 13:11 vde_switch
-rwxr-xr-x  1 root  wheel   55432 May  1 13:11 vde_vmnet
lrwxr-xr-x  1 root  wheel       7 May  1 13:11 vdecmd -> unixcmd
-rwxr-xr-x  1 root  wheel   50640 May  1 13:11 vdeterm
-rwxr-xr-x  1 root  wheel   72432 May  1 13:11 wirefilter
```
I have the networks.yaml
```
% cat .lima/_config/networks.yaml 
# Paths to vde executables. Because vde_vmnet is invoked via sudo it should be
# installed where only root can modify/replace it. This means also none of the
# parent directories should be writable by the user.
#
# The varRun directory also must not be writable by the user because it will
# include the vde_vmnet pid files. Those will be terminated via sudo, so replacing
# the pid files would allow killing of arbitrary privileged processes. varRun
# however MUST be writable by the daemon user.
#
# None of the paths segments may be symlinks, why it has to be /private/var
# instead of /var etc.
paths:
  vdeSwitch: /opt/vde/bin/vde_switch
  vdeVMNet: /opt/vde/bin/vde_vmnet
  varRun: /private/var/run/lima
  sudoers: /private/etc/sudoers.d/lima

group: everyone

networks:
  shared:
    mode: shared
    gateway: 192.168.105.1
    dhcpEnd: 192.168.105.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: en0
    # bridged mode doesn't have a gateway; dhcp is managed by outside network
  host:
    mode: host
    gateway: 192.168.106.1
    dhcpEnd: 192.168.106.254
    netmask: 255.255.255.0
```
I have default instance lima.yaml
```
% cat .lima/default/lima.yaml 
# Example to enable vmnet.framework
# This example requires Lima v0.7.0 or later.
# Older versions of Lima were using a different syntax for supporting vmnet.framework.
images:
- location: "https://cloud-images.ubuntu.com/releases/22.04/release-20220420/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
  digest: "sha256:de5e632e17b8965f2baf4ea6d2b824788e154d9a65df4fd419ec4019898e15cd"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release-20220420/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"
  digest: "sha256:66224c7fed99ff5a5539eda406c87bbfefe8af6ff6b47d92df3187832b5b5d4f"
# Fallback to the latest release image.
# Hint: run `limactl prune` to invalidate the cache
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"

mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
networks:
# The instance can get routable IP addresses from the vmnet framework using
# https://github.com/lima-vm/vde_vmnet. Available networks are defined in
# $LIMA_HOME/_config/networks.yaml. Supported network types are "host",
# "shared", or "bridged".
- lima: shared

```
I get this error ;
```
% limactl start --name default template://vmnet
? Creating an instance "default" Proceed with the current configuration
FATA[0001] can't read "/private/etc/sudoers.d/lima": open /private/etc/sudoers.d/lima: permission denied 
m@mypc [~] 
% ls -lth /private/etc/sudoers.d/lima
-r--r-----  1 root  wheel   2.0K May  1 18:49 /private/etc/sudoers.d/lima
m@mypc [~] 
```
I have the sudoers created as per recommendation ;
```
% cat !$
cat /private/etc/sudoers.d/lima
cat: /private/etc/sudoers.d/lima: Permission denied
m@mypc [~] 
% sudo cat /private/etc/sudoers.d/lima
%everyone ALL=(root:wheel) NOPASSWD:NOSETENV: /bin/mkdir -m 775 -p /private/var/run/lima

# Manage "bridged" network daemons

%everyone ALL=(daemon:everyone) NOPASSWD:NOSETENV: \
    /opt/vde/bin/vde_switch --pidfile=/private/var/run/lima/bridged_switch.pid --sock=/private/var/run/lima/bridged.ctl --group=everyone --dirmode=0770 --nostdin, \
    /usr/bin/pkill -F /private/var/run/lima/bridged_switch.pid

%everyone ALL=(root:wheel) NOPASSWD:NOSETENV: \
    /opt/vde/bin/vde_vmnet --pidfile=/private/var/run/lima/bridged_vmnet.pid --vde-group=everyone --vmnet-mode=bridged --vmnet-interface=en0 /private/var/run/lima/bridged.ctl, \
    /usr/bin/pkill -F /private/var/run/lima/bridged_vmnet.pid

# Manage "host" network daemons

%everyone ALL=(daemon:everyone) NOPASSWD:NOSETENV: \
    /opt/vde/bin/vde_switch --pidfile=/private/var/run/lima/host_switch.pid --sock=/private/var/run/lima/host.ctl --group=everyone --dirmode=0770 --nostdin, \
    /usr/bin/pkill -F /private/var/run/lima/host_switch.pid

%everyone ALL=(root:wheel) NOPASSWD:NOSETENV: \
    /opt/vde/bin/vde_vmnet --pidfile=/private/var/run/lima/host_vmnet.pid --vde-group=everyone --vmnet-mode=host --vmnet-gateway=192.168.106.1 --vmnet-dhcp-end=192.168.106.254 --vmnet-mask=255.255.255.0 /private/var/run/lima/host.ctl, \
    /usr/bin/pkill -F /private/var/run/lima/host_vmnet.pid

# Manage "shared" network daemons

%everyone ALL=(daemon:everyone) NOPASSWD:NOSETENV: \
    /opt/vde/bin/vde_switch --pidfile=/private/var/run/lima/shared_switch.pid --sock=/private/var/run/lima/shared.ctl --group=everyone --dirmode=0770 --nostdin, \
    /usr/bin/pkill -F /private/var/run/lima/shared_switch.pid

%everyone ALL=(root:wheel) NOPASSWD:NOSETENV: \
    /opt/vde/bin/vde_vmnet --pidfile=/private/var/run/lima/shared_vmnet.pid --vde-group=everyone --vmnet-mode=shared --vmnet-gateway=192.168.105.1 --vmnet-dhcp-end=192.168.105.254 --vmnet-mask=255.255.255.0 /private/var/run/lima/shared.ctl, \
    /usr/bin/pkill -F /private/var/run/lima/shared_vmnet.pid
m@mypc [~] 
% 
```
