### ISSUE TITLE
Attempting to mount a writable directory under a read-only directory doesn't work

### ISSUE THREAD

**Issue by UnoWho247** [lima-vm/lima#873]
### Description

Lima version `0.11.0` Mac OS Monterey

With the default configuration and adding an additional mount:
```
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
- location: "~/dev"
  writable: true
```

I would always receive the following message when starting the container:
```
INFO[0032] [hostagent] Mounting "/Users/gteu/dev" 
INFO[0032] [hostagent] fusermount3: user has no write access to mountpoint /Users/gteu/dev 
WARN[0064] [hostagent] failed to confirm whether /Users/gteu/dev [remote] is successfully mounted 
```

However, I was able to get the mount to work by making the following modification to lima.yaml (eliminating the home directory read-only mount):
```
mounts:
- location: "~/dev"
  writable: true
- location: "/tmp/lima"
  writable: true
```

This suggests that the home directory read-only directive prevented the sub directory writable directive. This feels like a bug? I believe I read somewhere that sub-directory mounts should override any parent directory settings. If that behavior is intended, some further documentation to indicate that fact would be helpful.

**Comment by jandubois** [comment]
I know that overlapping mounts do not work properly with sshfs (see #302). Have you tried using the `9p` mount type to see if it works there?

**Comment by Miro0o** [comment]
I got the same problem. Is there any way to do it without changing to other mount type? I need to mount a writable directory to lima for use of Harbor.

**Comment by jsoref** [comment]
Use a disk image that gets mounted in `/Volumes/VOLUME_NAME`?

**Comment by stevo-knievo** [comment]
I have the same issues.
I switched to `virtiofs` and now it works fine.
https://github.com/lima-vm/lima/blob/master/docs/vmtype.md#vz

**Comment by benatkin** [comment]
Seems like a documentation issue with maybe some upstream issues. Support doesn't seem to be missing where it's available on the underlying setup.

**Comment by jandubois** [comment]
> Is there any way to do it without changing to other mount type?

I have not tried this, but I think it might work: mount the 2 directories to non-overlapping locations inside the VM, now that Lima allows you to specify the `mountPoint`:

```yaml
mounts:
- location: "~"
- location: "~/data"
  mountPoint: /data
  writable: true
```

That way the mounts are not overlapping inside the VM.
