### ISSUE TITLE
unsuccessfully start a CentOS8 Stream vm

### ISSUE THREAD

**Issue by ronnin** [lima-vm/lima#884]
### Description

I was trying to start a CentOS8 Stream VM with the template:
```yaml
images:
  - location: https://cloud.centos.org/centos/8-stream/aarch64/images/CentOS-Stream-GenericCloud-8-20220125.1.aarch64.qcow2
    arch: 'aarch64'
mounts:
  - location: "~"
  - location: "/tmp/lima"
    writeable: true
```

The starting process was blocked on the step:
`
INFO[0047] [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
`

Work Env：
- lima version: 0.11.0 
- OS: macOS 12.4
- arch: M1 Max

Thanks for your work and help.
