### ISSUE TITLE
mountPoint configuration not working

### ISSUE THREAD

**Issue by cedws** [lima-vm/lima#906]
### Description

I would like to mount a path from the host to a specific path in the guest using the `mounts.[].mountPoint` setting, but this seems to have no effect. With the template below, the host path is mounted to `/Users/connoredwards/test`, not `/tmp`.

```yaml
images:
# Try to use release-yyyyMMdd image if available. Note that release-yyyyMMdd will be removed after several months.
- location: "https://cloud-images.ubuntu.com/releases/22.04/release-20220420/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
  digest: "sha256:de5e632e17b8965f2baf4ea6d2b824788e154d9a65df4fd419ec4019898e15cd"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release-20220420/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"
  digest: "sha256:66224c7fed99ff5a5539eda406c87bbfefe8af6ff6b47d92df3187832b5b5d4f"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
  arch: "aarch64"

mounts:
  - location: "/Users/connoredwards/test"
    mountPoint: "/tmp"
    writable: false
```

```
connoredwards@lima-test:/Users/connoredwards$ ls
test
connoredwards@lima-test:/Users/connoredwards$ ls /tmp/test
ls: cannot access '/tmp/test': No such file or directory
```

```
root@lima-test:/mnt/lima-cidata# cat lima.env
LIMA_CIDATA_NAME=test
LIMA_CIDATA_USER=connoredwards
LIMA_CIDATA_UID=501
LIMA_CIDATA_MOUNTS=1
LIMA_CIDATA_MOUNTS_0_MOUNTPOINT=/Users/connoredwards/test
LIMA_CIDATA_MOUNTTYPE=reverse-sshfs
LIMA_CIDATA_CONTAINERD_USER=1
LIMA_CIDATA_CONTAINERD_SYSTEM=
LIMA_CIDATA_SLIRP_DNS=192.168.5.3
LIMA_CIDATA_SLIRP_GATEWAY=192.168.5.2
LIMA_CIDATA_SLIRP_IP_ADDRESS=192.168.5.15
LIMA_CIDATA_UDP_DNS_LOCAL_PORT=55406
LIMA_CIDATA_TCP_DNS_LOCAL_PORT=49995
```

Lima version: `limactl version 0.11.0`
Host: macOS 11.4 (M1)
