### ISSUE TITLE
Mountpoints cannot include whitespace

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#933]
### Description

Lima does not support mounting locations containing whitespace, e.g.

```yaml
mounts:
- location: "~/foo bar"
  writable: true
```

This obviously affects users whose host username contains a space.

Known problem spots:
* `lima.env` does not quote `LIMA_CIDATA_MOUNTS_NNN_MOUNTPOINT`
* `reversesshfs.Prepare` doesn't quote the argument to `mkdir -p`
* `reversesshfs.Start` doesn't quote the local and remote path arguments to `sshfs`

There are probably more...
